/**
 * SmartInvest educational symbol universe (HK + US + major indices).
 * Single source for embedded fallback; mirrored to public/data/invest-market-snapshot.json.
 */

import type { MarketIndex, MarketQuote, MarketSnapshot } from "@/lib/investMarket";

export const INVEST_UNIVERSE_AS_OF = "2026-08-10T16:00:00+08:00";

export const DEFAULT_WATCHLIST_IDS = [
  "0700.HK",
  "2800.HK",
  "3033.HK",
  "AAPL",
  "NVDA",
  "SPY",
] as const;

const INDICES: MarketIndex[] = [
  {
    id: "hsi",
    market: "HK",
    symbol: "HSI",
    nameZh: "恒生指數",
    last: 17520.4,
    changePct: 0.85,
    trendNoteZh: "港股藍籌大市指標，適合觀察本地風險氣氛。",
  },
  {
    id: "hscei",
    market: "HK",
    symbol: "HSCEI",
    nameZh: "恒生中國企業指數",
    last: 6120.5,
    changePct: 0.62,
    trendNoteZh: "H 股代表指數，教學上對照內地企業在港表現。",
  },
  {
    id: "hstech",
    market: "HK",
    symbol: "HSTECH",
    last: 3820.1,
    changePct: 1.42,
    nameZh: "恒生科技指數",
    trendNoteZh: "科技板塊波動較大，適合學波動率同倉位控制。",
  },
  {
    id: "dji",
    market: "US",
    symbol: "DJI",
    nameZh: "道瓊斯工業平均",
    last: 39850.2,
    changePct: 0.28,
    trendNoteZh: "美股傳統藍籌指數，對照大型工業／金融股。",
  },
  {
    id: "spx",
    market: "US",
    symbol: "SPX",
    nameZh: "標普 500",
    last: 5480.2,
    changePct: 0.38,
    trendNoteZh: "廣基指數，教學上常用嚟對照單一股票風險。",
  },
  {
    id: "ndx",
    market: "US",
    symbol: "NDX",
    nameZh: "納斯達克 100",
    last: 19210.5,
    changePct: 0.91,
    trendNoteZh: "科技權重高，示範「集中度風險」。",
  },
];

const NAMES: MarketQuote[] = [
  // —— HK tech ——
  {
    id: "0700.HK",
    market: "HK",
    symbol: "0700.HK",
    nameZh: "騰訊控股",
    category: "tech",
    last: 382.4,
    changePct: 1.1,
    currency: "HKD",
    riskLevel: "medium",
    blurbZh: "港股大型科技代表，流動性高。",
  },
  {
    id: "9988.HK",
    market: "HK",
    symbol: "9988.HK",
    nameZh: "阿里巴巴－Ｗ",
    category: "tech",
    last: 88.5,
    changePct: 0.6,
    currency: "HKD",
    riskLevel: "medium",
    blurbZh: "大型新經濟股，適合對照雙重上市概念。",
  },
  {
    id: "3690.HK",
    market: "HK",
    symbol: "3690.HK",
    nameZh: "美團－Ｗ",
    category: "tech",
    last: 118.2,
    changePct: 0.9,
    currency: "HKD",
    riskLevel: "high",
    blurbZh: "本地生活／配送平台，波動通常高於藍籌。",
  },
  {
    id: "1810.HK",
    market: "HK",
    symbol: "1810.HK",
    nameZh: "小米集團－Ｗ",
    category: "tech",
    last: 18.6,
    changePct: 1.4,
    currency: "HKD",
    riskLevel: "medium",
    blurbZh: "消費電子＋互聯網生態代表。",
  },
  {
    id: "9618.HK",
    market: "HK",
    symbol: "9618.HK",
    nameZh: "京東集團－ＳＷ",
    category: "tech",
    last: 112.4,
    changePct: 0.5,
    currency: "HKD",
    riskLevel: "medium",
    blurbZh: "電商物流一體化代表。",
  },
  {
    id: "1024.HK",
    market: "HK",
    symbol: "1024.HK",
    nameZh: "快手－Ｗ",
    category: "tech",
    last: 48.3,
    changePct: -0.8,
    currency: "HKD",
    riskLevel: "high",
    blurbZh: "短視頻／內容平台，消息敏感度高。",
  },
  {
    id: "9888.HK",
    market: "HK",
    symbol: "9888.HK",
    nameZh: "百度集團－ＳＷ",
    category: "tech",
    last: 92.1,
    changePct: 0.3,
    currency: "HKD",
    riskLevel: "medium",
    blurbZh: "搜尋／AI 概念大型科網股。",
  },
  {
    id: "9999.HK",
    market: "HK",
    symbol: "9999.HK",
    nameZh: "網易－Ｓ",
    category: "tech",
    last: 148.6,
    changePct: 0.7,
    currency: "HKD",
    riskLevel: "medium",
    blurbZh: "遊戲同內容生態代表。",
  },
  {
    id: "9626.HK",
    market: "HK",
    symbol: "9626.HK",
    nameZh: "嗶哩嗶哩－Ｗ",
    category: "tech",
    last: 142.8,
    changePct: 1.8,
    currency: "HKD",
    riskLevel: "high",
    blurbZh: "年輕用戶內容平台，波動較大。",
  },
  {
    id: "2015.HK",
    market: "HK",
    symbol: "2015.HK",
    nameZh: "理想汽車－Ｗ",
    category: "tech",
    last: 86.4,
    changePct: -1.2,
    currency: "HKD",
    riskLevel: "high",
    blurbZh: "新能源車新經濟股，適合學高波動行業。",
  },
  {
    id: "9866.HK",
    market: "HK",
    symbol: "9866.HK",
    nameZh: "蔚來－ＳＷ",
    category: "tech",
    last: 38.2,
    changePct: -2.1,
    currency: "HKD",
    riskLevel: "high",
    blurbZh: "新能源車，盈利同銷量預期敏感。",
  },
  {
    id: "1211.HK",
    market: "HK",
    symbol: "1211.HK",
    nameZh: "比亞迪股份",
    category: "tech",
    last: 248.0,
    changePct: 0.9,
    currency: "HKD",
    riskLevel: "medium",
    blurbZh: "新能源車／電池龍頭之一。",
  },
  {
    id: "0175.HK",
    market: "HK",
    symbol: "0175.HK",
    nameZh: "吉利汽車",
    category: "consumer",
    last: 12.8,
    changePct: 0.4,
    currency: "HKD",
    riskLevel: "medium",
    blurbZh: "汽車製造消費週期股。",
  },
  // —— HK finance / bluechip ——
  {
    id: "0005.HK",
    market: "HK",
    symbol: "0005.HK",
    nameZh: "匯豐控股",
    category: "finance",
    last: 68.2,
    changePct: -0.3,
    currency: "HKD",
    riskLevel: "medium",
    blurbZh: "金融藍籌，常睇息率同利率環境。",
  },
  {
    id: "1299.HK",
    market: "HK",
    symbol: "1299.HK",
    nameZh: "友邦保險",
    category: "finance",
    last: 58.4,
    changePct: 0.2,
    currency: "HKD",
    riskLevel: "medium",
    blurbZh: "亞洲保險龍頭藍籌。",
  },
  {
    id: "2318.HK",
    market: "HK",
    symbol: "2318.HK",
    nameZh: "中國平安",
    category: "finance",
    last: 42.6,
    changePct: -0.5,
    currency: "HKD",
    riskLevel: "medium",
    blurbZh: "綜合金融，保險＋銀行業務。",
  },
  {
    id: "0388.HK",
    market: "HK",
    symbol: "0388.HK",
    nameZh: "香港交易所",
    category: "finance",
    last: 268.0,
    changePct: 0.8,
    currency: "HKD",
    riskLevel: "medium",
    blurbZh: "市場成交同 IPO 氣氛敏感。",
  },
  {
    id: "1398.HK",
    market: "HK",
    symbol: "1398.HK",
    nameZh: "工商銀行",
    category: "finance",
    last: 4.62,
    changePct: 0.1,
    currency: "HKD",
    riskLevel: "medium",
    blurbZh: "大型中資銀行 H 股。",
  },
  {
    id: "0939.HK",
    market: "HK",
    symbol: "0939.HK",
    nameZh: "建設銀行",
    category: "finance",
    last: 5.48,
    changePct: 0.2,
    currency: "HKD",
    riskLevel: "medium",
    blurbZh: "大型中資銀行藍籌。",
  },
  {
    id: "3988.HK",
    market: "HK",
    symbol: "3988.HK",
    nameZh: "中國銀行",
    category: "finance",
    last: 3.56,
    changePct: 0.0,
    currency: "HKD",
    riskLevel: "medium",
    blurbZh: "大型中資銀行，息率教學常用例子。",
  },
  {
    id: "2628.HK",
    market: "HK",
    symbol: "2628.HK",
    nameZh: "中國人壽",
    category: "finance",
    last: 14.2,
    changePct: -0.4,
    currency: "HKD",
    riskLevel: "medium",
    blurbZh: "大型壽險 H 股。",
  },
  {
    id: "0011.HK",
    market: "HK",
    symbol: "0011.HK",
    nameZh: "恒生銀行",
    category: "bluechip",
    last: 98.5,
    changePct: 0.3,
    currency: "HKD",
    riskLevel: "low",
    blurbZh: "本地銀行藍籌。",
  },
  {
    id: "0941.HK",
    market: "HK",
    symbol: "0941.HK",
    nameZh: "中國移動",
    category: "bluechip",
    last: 76.8,
    changePct: 0.4,
    currency: "HKD",
    riskLevel: "low",
    blurbZh: "電訊藍籌，防禦／息率教學例子。",
  },
  {
    id: "0001.HK",
    market: "HK",
    symbol: "0001.HK",
    nameZh: "長和",
    category: "bluechip",
    last: 42.1,
    changePct: -0.2,
    currency: "HKD",
    riskLevel: "medium",
    blurbZh: "綜合企業藍籌。",
  },
  {
    id: "0002.HK",
    market: "HK",
    symbol: "0002.HK",
    nameZh: "中電控股",
    category: "bluechip",
    last: 64.3,
    changePct: 0.1,
    currency: "HKD",
    riskLevel: "low",
    blurbZh: "公用事業藍籌，波動相對較低。",
  },
  {
    id: "0003.HK",
    market: "HK",
    symbol: "0003.HK",
    nameZh: "香港中華煤氣",
    category: "bluechip",
    last: 6.12,
    changePct: 0.0,
    currency: "HKD",
    riskLevel: "low",
    blurbZh: "公用事業藍籌。",
  },
  {
    id: "0016.HK",
    market: "HK",
    symbol: "0016.HK",
    nameZh: "新鴻基地產",
    category: "bluechip",
    last: 78.4,
    changePct: -0.6,
    currency: "HKD",
    riskLevel: "medium",
    blurbZh: "地產藍籌，利率同樓市敏感。",
  },
  // —— HK consumer ——
  {
    id: "2020.HK",
    market: "HK",
    symbol: "2020.HK",
    nameZh: "安踏體育",
    category: "consumer",
    last: 82.6,
    changePct: 0.7,
    currency: "HKD",
    riskLevel: "medium",
    blurbZh: "運動服飾消費股。",
  },
  {
    id: "2319.HK",
    market: "HK",
    symbol: "2319.HK",
    nameZh: "蒙牛乳業",
    category: "consumer",
    last: 16.4,
    changePct: -0.3,
    currency: "HKD",
    riskLevel: "medium",
    blurbZh: "乳品消費必需品代表。",
  },
  {
    id: "0669.HK",
    market: "HK",
    symbol: "0669.HK",
    nameZh: "創科實業",
    category: "consumer",
    last: 98.2,
    changePct: 1.0,
    currency: "HKD",
    riskLevel: "medium",
    blurbZh: "電動工具／消費耐用品。",
  },
  {
    id: "2382.HK",
    market: "HK",
    symbol: "2382.HK",
    nameZh: "舜宇光學科技",
    category: "tech",
    last: 58.9,
    changePct: 1.5,
    currency: "HKD",
    riskLevel: "high",
    blurbZh: "光學部件，電子供應鏈波動股。",
  },
  {
    id: "0291.HK",
    market: "HK",
    symbol: "0291.HK",
    nameZh: "華潤啤酒",
    category: "consumer",
    last: 28.4,
    changePct: 0.2,
    currency: "HKD",
    riskLevel: "medium",
    blurbZh: "消費飲料股。",
  },
  {
    id: "1928.HK",
    market: "HK",
    symbol: "1928.HK",
    nameZh: "金沙中國",
    category: "consumer",
    last: 18.9,
    changePct: -0.9,
    currency: "HKD",
    riskLevel: "high",
    blurbZh: "博彩旅遊週期股。",
  },
  // —— HK ETFs ——
  {
    id: "2800.HK",
    market: "HK",
    symbol: "2800.HK",
    nameZh: "盈富基金",
    category: "etf",
    last: 18.9,
    changePct: 0.5,
    currency: "HKD",
    riskLevel: "low",
    blurbZh: "追蹤恒指嘅 ETF，適合學分散。",
  },
  {
    id: "3033.HK",
    market: "HK",
    symbol: "3033.HK",
    nameZh: "南方恒生科技",
    category: "etf",
    last: 5.12,
    changePct: 1.3,
    currency: "HKD",
    riskLevel: "medium",
    blurbZh: "追蹤恒生科技指數嘅熱門 ETF。",
  },
  {
    id: "3067.HK",
    market: "HK",
    symbol: "3067.HK",
    nameZh: "安碩恒生科技",
    category: "etf",
    last: 5.08,
    changePct: 1.2,
    currency: "HKD",
    riskLevel: "medium",
    blurbZh: "另一隻恒生科技主題 ETF。",
  },
  {
    id: "2822.HK",
    market: "HK",
    symbol: "2822.HK",
    nameZh: "南方 A50",
    category: "etf",
    last: 12.4,
    changePct: 0.4,
    currency: "HKD",
    riskLevel: "medium",
    blurbZh: "A 股大型股主題 ETF（教學用）。",
  },
  {
    id: "2801.HK",
    market: "HK",
    symbol: "2801.HK",
    nameZh: "安碩中國",
    category: "etf",
    last: 22.6,
    changePct: 0.6,
    currency: "HKD",
    riskLevel: "medium",
    blurbZh: "中國股票主題 ETF。",
  },
  {
    id: "2828.HK",
    market: "HK",
    symbol: "2828.HK",
    nameZh: "恒生中國企業",
    category: "etf",
    last: 68.5,
    changePct: 0.5,
    currency: "HKD",
    riskLevel: "medium",
    blurbZh: "追蹤恒生中國企業指數嘅 ETF。",
  },
  {
    id: "demo-penny.HK",
    market: "HK",
    symbol: "DEMO.PENNY",
    nameZh: "示範仙股（虛構）",
    category: "penny",
    last: 0.082,
    changePct: -4.2,
    currency: "HKD",
    riskLevel: "very_high",
    blurbZh:
      "虛構低價股示範：流動性差、波動極大——新手應視為高風險教材，唔係入手對象。",
  },
  // —— US tech ——
  {
    id: "AAPL",
    market: "US",
    symbol: "AAPL",
    nameZh: "蘋果",
    category: "tech",
    last: 214.3,
    changePct: 0.7,
    currency: "USD",
    riskLevel: "medium",
    blurbZh: "美股大型科技，適合學報價單位。",
  },
  {
    id: "MSFT",
    market: "US",
    symbol: "MSFT",
    nameZh: "微軟",
    category: "tech",
    last: 428.1,
    changePct: 0.4,
    currency: "USD",
    riskLevel: "medium",
    blurbZh: "大型軟件／雲端代表。",
  },
  {
    id: "NVDA",
    market: "US",
    symbol: "NVDA",
    nameZh: "輝達",
    category: "tech",
    last: 118.5,
    changePct: 2.1,
    currency: "USD",
    riskLevel: "high",
    blurbZh: "AI／半導體高關注股，波動大。",
  },
  {
    id: "GOOGL",
    market: "US",
    symbol: "GOOGL",
    nameZh: "Alphabet（谷歌）",
    category: "tech",
    last: 176.2,
    changePct: 0.5,
    currency: "USD",
    riskLevel: "medium",
    blurbZh: "搜尋／雲端大型科技。",
  },
  {
    id: "AMZN",
    market: "US",
    symbol: "AMZN",
    nameZh: "亞馬遜",
    category: "tech",
    last: 192.4,
    changePct: 0.8,
    currency: "USD",
    riskLevel: "medium",
    blurbZh: "電商＋雲端（AWS）。",
  },
  {
    id: "META",
    market: "US",
    symbol: "META",
    nameZh: "Meta",
    category: "tech",
    last: 512.6,
    changePct: 1.0,
    currency: "USD",
    riskLevel: "medium",
    blurbZh: "社交媒體／廣告大型科技。",
  },
  {
    id: "TSLA",
    market: "US",
    symbol: "TSLA",
    nameZh: "特斯拉",
    category: "tech",
    last: 248.8,
    changePct: -1.5,
    currency: "USD",
    riskLevel: "high",
    blurbZh: "電動車／高波動成長股教學例子。",
  },
  {
    id: "AVGO",
    market: "US",
    symbol: "AVGO",
    nameZh: "博通",
    category: "tech",
    last: 168.4,
    changePct: 0.9,
    currency: "USD",
    riskLevel: "medium",
    blurbZh: "半導體／基礎設施芯片。",
  },
  {
    id: "AMD",
    market: "US",
    symbol: "AMD",
    nameZh: "超微半導體",
    category: "tech",
    last: 142.3,
    changePct: 1.6,
    currency: "USD",
    riskLevel: "high",
    blurbZh: "半導體競爭格局敏感。",
  },
  {
    id: "INTC",
    market: "US",
    symbol: "INTC",
    nameZh: "英特爾",
    category: "tech",
    last: 28.6,
    changePct: -0.8,
    currency: "USD",
    riskLevel: "high",
    blurbZh: "傳統半導體巨頭，轉型故事波動大。",
  },
  {
    id: "NFLX",
    market: "US",
    symbol: "NFLX",
    nameZh: "網飛",
    category: "tech",
    last: 682.1,
    changePct: 0.6,
    currency: "USD",
    riskLevel: "medium",
    blurbZh: "串流媒體代表。",
  },
  {
    id: "ORCL",
    market: "US",
    symbol: "ORCL",
    nameZh: "甲骨文",
    category: "tech",
    last: 148.2,
    changePct: 0.4,
    currency: "USD",
    riskLevel: "medium",
    blurbZh: "企業軟件／雲端。",
  },
  {
    id: "CRM",
    market: "US",
    symbol: "CRM",
    nameZh: "Salesforce",
    category: "tech",
    last: 268.5,
    changePct: 0.3,
    currency: "USD",
    riskLevel: "medium",
    blurbZh: "企業 SaaS 代表。",
  },
  // —— US finance ——
  {
    id: "BRK.B",
    market: "US",
    symbol: "BRK.B",
    nameZh: "伯克希爾（B）",
    category: "finance",
    last: 428.6,
    changePct: 0.2,
    currency: "USD",
    riskLevel: "low",
    blurbZh: "多元控股，防禦型金融教學例子。",
  },
  {
    id: "JPM",
    market: "US",
    symbol: "JPM",
    nameZh: "摩根大通",
    category: "finance",
    last: 208.4,
    changePct: 0.5,
    currency: "USD",
    riskLevel: "medium",
    blurbZh: "美資大型銀行。",
  },
  {
    id: "V",
    market: "US",
    symbol: "V",
    nameZh: "Visa",
    category: "finance",
    last: 278.2,
    changePct: 0.3,
    currency: "USD",
    riskLevel: "medium",
    blurbZh: "支付網絡金融股。",
  },
  {
    id: "MA",
    market: "US",
    symbol: "MA",
    nameZh: "Mastercard",
    category: "finance",
    last: 468.1,
    changePct: 0.4,
    currency: "USD",
    riskLevel: "medium",
    blurbZh: "支付網絡，對照 Visa。",
  },
  {
    id: "BAC",
    market: "US",
    symbol: "BAC",
    nameZh: "美國銀行",
    category: "finance",
    last: 38.9,
    changePct: 0.6,
    currency: "USD",
    riskLevel: "medium",
    blurbZh: "大型零售銀行。",
  },
  {
    id: "GS",
    market: "US",
    symbol: "GS",
    nameZh: "高盛",
    category: "finance",
    last: 498.2,
    changePct: 0.7,
    currency: "USD",
    riskLevel: "medium",
    blurbZh: "投資銀行代表。",
  },
  // —— US consumer ——
  {
    id: "WMT",
    market: "US",
    symbol: "WMT",
    nameZh: "沃爾瑪",
    category: "consumer",
    last: 72.4,
    changePct: 0.2,
    currency: "USD",
    riskLevel: "low",
    blurbZh: "零售必需消費防禦股。",
  },
  {
    id: "COST",
    market: "US",
    symbol: "COST",
    nameZh: "好市多",
    category: "consumer",
    last: 868.5,
    changePct: 0.5,
    currency: "USD",
    riskLevel: "medium",
    blurbZh: "會員制零售。",
  },
  {
    id: "HD",
    market: "US",
    symbol: "HD",
    nameZh: "家得寶",
    category: "consumer",
    last: 368.2,
    changePct: -0.3,
    currency: "USD",
    riskLevel: "medium",
    blurbZh: "家居裝修零售週期股。",
  },
  {
    id: "MCD",
    market: "US",
    symbol: "MCD",
    nameZh: "麥當勞",
    category: "consumer",
    last: 268.4,
    changePct: 0.1,
    currency: "USD",
    riskLevel: "low",
    blurbZh: "全球快餐消費股。",
  },
  {
    id: "NKE",
    market: "US",
    symbol: "NKE",
    nameZh: "耐克",
    category: "consumer",
    last: 78.6,
    changePct: -0.7,
    currency: "USD",
    riskLevel: "medium",
    blurbZh: "運動品牌可選消費。",
  },
  {
    id: "PG",
    market: "US",
    symbol: "PG",
    nameZh: "寶潔",
    category: "consumer",
    last: 168.2,
    changePct: 0.1,
    currency: "USD",
    riskLevel: "low",
    blurbZh: "日用必需消費防禦股。",
  },
  {
    id: "KO",
    market: "US",
    symbol: "KO",
    nameZh: "可口可樂",
    category: "consumer",
    last: 64.8,
    changePct: 0.2,
    currency: "USD",
    riskLevel: "low",
    blurbZh: "飲料防禦型藍籌。",
  },
  // —— US healthcare ——
  {
    id: "JNJ",
    market: "US",
    symbol: "JNJ",
    nameZh: "強生",
    category: "healthcare",
    last: 158.6,
    changePct: -0.2,
    currency: "USD",
    riskLevel: "low",
    blurbZh: "醫藥消費防禦代表。",
  },
  {
    id: "UNH",
    market: "US",
    symbol: "UNH",
    nameZh: "聯合健康",
    category: "healthcare",
    last: 528.4,
    changePct: 0.3,
    currency: "USD",
    riskLevel: "medium",
    blurbZh: "醫療保險大型股。",
  },
  {
    id: "LLY",
    market: "US",
    symbol: "LLY",
    nameZh: "禮來",
    category: "healthcare",
    last: 812.6,
    changePct: 1.2,
    currency: "USD",
    riskLevel: "medium",
    blurbZh: "製藥成長股教學例子。",
  },
  {
    id: "PFE",
    market: "US",
    symbol: "PFE",
    nameZh: "輝瑞",
    category: "healthcare",
    last: 28.4,
    changePct: -0.4,
    currency: "USD",
    riskLevel: "medium",
    blurbZh: "大型製藥。",
  },
  // —— US energy ——
  {
    id: "XOM",
    market: "US",
    symbol: "XOM",
    nameZh: "埃克森美孚",
    category: "energy",
    last: 112.8,
    changePct: 1.2,
    currency: "USD",
    riskLevel: "medium",
    blurbZh: "能源週期股示範。",
  },
  {
    id: "CVX",
    market: "US",
    symbol: "CVX",
    nameZh: "雪佛龍",
    category: "energy",
    last: 156.2,
    changePct: 0.9,
    currency: "USD",
    riskLevel: "medium",
    blurbZh: "大型綜合石油公司。",
  },
  // —— US ETFs ——
  {
    id: "SPY",
    market: "US",
    symbol: "SPY",
    nameZh: "SPDR S&P 500 ETF",
    category: "etf",
    last: 548.2,
    changePct: 0.35,
    currency: "USD",
    riskLevel: "low",
    blurbZh: "最流通嘅標普 500 ETF。",
  },
  {
    id: "VOO",
    market: "US",
    symbol: "VOO",
    nameZh: "Vanguard S&P 500 ETF",
    category: "etf",
    last: 512.4,
    changePct: 0.35,
    currency: "USD",
    riskLevel: "low",
    blurbZh: "廣基指數 ETF，新手核心學習倉常用。",
  },
  {
    id: "QQQ",
    market: "US",
    symbol: "QQQ",
    nameZh: "Invesco QQQ",
    category: "etf",
    last: 478.6,
    changePct: 0.85,
    currency: "USD",
    riskLevel: "medium",
    blurbZh: "追蹤納指 100，科技權重高。",
  },
  {
    id: "IWM",
    market: "US",
    symbol: "IWM",
    nameZh: "iShares 羅素 2000",
    category: "etf",
    last: 218.4,
    changePct: 0.4,
    currency: "USD",
    riskLevel: "medium",
    blurbZh: "美股小型股指數 ETF。",
  },
  {
    id: "VTI",
    market: "US",
    symbol: "VTI",
    nameZh: "Vanguard 全市場",
    category: "etf",
    last: 278.2,
    changePct: 0.36,
    currency: "USD",
    riskLevel: "low",
    blurbZh: "覆蓋更廣嘅美股全市場 ETF。",
  },
  {
    id: "DIA",
    market: "US",
    symbol: "DIA",
    nameZh: "SPDR 道指 ETF",
    category: "etf",
    last: 398.5,
    changePct: 0.28,
    currency: "USD",
    riskLevel: "low",
    blurbZh: "追蹤道瓊斯工業平均。",
  },
];

/** Finnhub quote symbol overrides (indices / edge cases). */
export const FINNHUB_INDEX_SYMBOLS: Record<string, string> = {
  hsi: "^HSI",
  hscei: "^HSCE",
  hstech: "3033.HK", // free-tier friendly proxy via HSTECH ETF
  dji: "^DJI",
  spx: "^GSPC",
  ndx: "^NDX",
};

/** Map app symbol → Finnhub symbol when formats differ. */
export function toFinnhubSymbol(symbol: string): string | null {
  if (!symbol || symbol.startsWith("DEMO")) return null;
  // Finnhub HK often accepts both 0700.HK and 700.HK; keep padded form first.
  return symbol;
}

export function buildEducationalUniverseSnapshot(): MarketSnapshot {
  return {
    version: 2,
    label: "示範／學習用",
    source:
      "CookingMAMA educational sample snapshot (not a live exchange feed)",
    asOf: INVEST_UNIVERSE_AS_OF,
    disclaimerZh:
      "投資有風險，內容僅供學習。以下為示範市場快照，唔係實時報價，亦唔構成買賣建議。",
    indices: INDICES.map((i) => ({ ...i })),
    names: NAMES.map((n) => ({ ...n })),
  };
}

export function universeStats() {
  const hk = NAMES.filter((n) => n.market === "HK" && !n.symbol.startsWith("DEMO"));
  const us = NAMES.filter((n) => n.market === "US");
  const demo = NAMES.filter((n) => n.symbol.startsWith("DEMO"));
  return {
    indices: INDICES.length,
    hkNames: hk.length,
    usNames: us.length,
    demoNames: demo.length,
    totalNames: NAMES.length,
  };
}
