/**
 * SmartJP — 每課完整學習內容（詞彙・讀法・例句・解說・練習）
 * Generated by scripts/build-jp-content.mjs — edit source scripts to regenerate.
 */

import type { LessonStudyContent } from "@/lib/japaneseCourse";

export const LESSON_STUDY_CONTENT: Record<string, LessonStudyContent> = {
  "beg-1-1": {
    vocab: [
      { ja: "あ", reading: "あ", meaningZh: "あ行第一音", romaji: "a" },
      { ja: "い", reading: "い", meaningZh: "あ行第二音", romaji: "i" },
      { ja: "う", reading: "う", meaningZh: "あ行第三音", romaji: "u" },
      { ja: "え", reading: "え", meaningZh: "あ行第四音", romaji: "e" },
      { ja: "お", reading: "お", meaningZh: "あ行第五音", romaji: "o" },
      { ja: "か", reading: "か", meaningZh: "か行", romaji: "ka" },
      { ja: "き", reading: "き", meaningZh: "か行", romaji: "ki" },
      { ja: "く", reading: "く", meaningZh: "か行", romaji: "ku" },
      { ja: "な", reading: "な", meaningZh: "な行", romaji: "na" },
      { ja: "に", reading: "に", meaningZh: "な行", romaji: "ni" }
    ],
    examples: [
      { ja: "あいうえお", reading: "あいうえお", meaningZh: "あ行五個音" },
      { ja: "なにぬねの", reading: "なにぬねの", meaningZh: "な行五個音" }
    ],
    tipsZh: [
      "平假名係日語基本表音文字；每一個假名對應一個音節。",
      "あ行：あ・い・う・え・お；か行加「k」輔音；な行加「n」輔音。",
      "讀法（讀み方）而家就係假名本身；入門階段跟羅馬字一齊記會更快。"
    ],
    practiceZh: [
      "大聲跟讀あ行～な行各三遍。",
      "遮住羅馬字，只睇假名讀出聲。",
      "默寫か行同な行。"
    ],
  },
  "beg-1-2": {
    vocab: [
      { ja: "は", reading: "は", meaningZh: "は行（助詞讀わ）", romaji: "ha" },
      { ja: "ひ", reading: "ひ", meaningZh: "は行", romaji: "hi" },
      { ja: "ふ", reading: "ふ", meaningZh: "は行", romaji: "fu" },
      { ja: "ま", reading: "ま", meaningZh: "ま行", romaji: "ma" },
      { ja: "や", reading: "や", meaningZh: "や行", romaji: "ya" },
      { ja: "ら", reading: "ら", meaningZh: "ら行", romaji: "ra" },
      { ja: "わ", reading: "わ", meaningZh: "わ行", romaji: "wa" },
      { ja: "ん", reading: "ん", meaningZh: "撥音", romaji: "n" },
      { ja: "が", reading: "が", meaningZh: "濁音が行", romaji: "ga" },
      { ja: "ぱ", reading: "ぱ", meaningZh: "半濁音ぱ行", romaji: "pa" },
      { ja: "こんにちは", reading: "こんにちは", meaningZh: "午安／你好", romaji: "konnichiwa" }
    ],
    examples: [
      { ja: "こんにちは", reading: "こんにちは", meaningZh: "午安／你好" },
      { ja: "ほん", reading: "ほん", meaningZh: "書（本）" }
    ],
    tipsZh: [
      "濁音：か→が、さ→ざ、た→だ、は→ば；半濁音：は→ぱ。",
      "「ん」係唯一唔以元音結尾嘅假名。",
      "打招呼「こんにちは」最後係「は」但讀「わ」。"
    ],
    practiceZh: [
      "寫齊は行・ま行・や行・ら行・わ行・ん。",
      "練習が・ざ・だ・ば・ぱ各行。",
      "聽寫：ほん、はな、やま。"
    ],
  },
  "beg-1-3": {
    vocab: [
      { ja: "あさ", reading: "あさ", meaningZh: "朝／早晨", romaji: "asa" },
      { ja: "ひる", reading: "ひる", meaningZh: "晝／中午", romaji: "hiru" },
      { ja: "よる", reading: "よる", meaningZh: "夜", romaji: "yoru" },
      { ja: "ねこ", reading: "ねこ", meaningZh: "貓", romaji: "neko" },
      { ja: "いぬ", reading: "いぬ", meaningZh: "狗", romaji: "inu" },
      { ja: "みず", reading: "みず", meaningZh: "水", romaji: "mizu" }
    ],
    examples: [
      { ja: "あさです", reading: "あさです", meaningZh: "而家係朝早" },
      { ja: "ねこがいます", reading: "ねこがいます", meaningZh: "有隻貓" }
    ],
    tipsZh: [
      "聽寫重點係「聽音→寫假名」，唔好靠估意思。",
      "容易混淆：き／さ、ぬ／め、わ／れ——慢慢對照筆形。"
    ],
    practiceZh: [
      "請人讀 20 個假名你寫低。",
      "對答案後，錯嘅假名重寫五次。",
      "用錯題再聽寫一輪。"
    ],
  },
  "beg-2-1": {
    vocab: [
      { ja: "ア", reading: "ア", meaningZh: "片假名あ", romaji: "a" },
      { ja: "イ", reading: "イ", meaningZh: "片假名い", romaji: "i" },
      { ja: "ウ", reading: "ウ", meaningZh: "片假名う", romaji: "u" },
      { ja: "カ", reading: "カ", meaningZh: "片假名か", romaji: "ka" },
      { ja: "ナ", reading: "ナ", meaningZh: "片假名な", romaji: "na" },
      { ja: "コーヒー", reading: "コーヒー", meaningZh: "咖啡", romaji: "kōhī" },
      { ja: "ノート", reading: "ノート", meaningZh: "筆記簿", romaji: "nōto" },
      { ja: "パン", reading: "パン", meaningZh: "麵包", romaji: "pan" }
    ],
    examples: [
      { ja: "コーヒーをのみます", reading: "コーヒーをのみます", meaningZh: "飲咖啡" },
      { ja: "ノートがあります", reading: "ノートがあります", meaningZh: "有筆記簿" }
    ],
    tipsZh: [
      "片假名多用嚟寫外來語、擬聲詞、強調。",
      "讀法同平假名對應：ア＝あ、カ＝か。"
    ],
    practiceZh: [
      "並排抄寫：あ／ア、か／カ、な／ナ。",
      "讀出：コーヒー、ノート、パン。",
      "由平假名轉換十個音到片假名。"
    ],
  },
  "beg-2-2": {
    vocab: [
      { ja: "タクシー", reading: "タクシー", meaningZh: "的士", romaji: "takushī" },
      { ja: "バス", reading: "バス", meaningZh: "巴士", romaji: "basu" },
      { ja: "ホテル", reading: "ホテル", meaningZh: "酒店", romaji: "hoteru" },
      { ja: "スーパー", reading: "スーパー", meaningZh: "超市", romaji: "sūpā" },
      { ja: "ゲーム", reading: "ゲーム", meaningZh: "遊戲", romaji: "gēmu" },
      { ja: "パソコン", reading: "パソコン", meaningZh: "電腦", romaji: "pasokon" }
    ],
    examples: [
      { ja: "タクシーにのります", reading: "タクシーにのります", meaningZh: "搭的士" },
      { ja: "ホテルにいきます", reading: "ホテルにいきます", meaningZh: "去酒店" }
    ],
    tipsZh: [
      "長音用「ー」：コーヒー、スーパー。",
      "促音「ッ」令後面子音停一拍：ベッド、コップ。"
    ],
    practiceZh: [
      "讀出タクシー・バス・ホテル。",
      "聽寫 10 個外來語（包長音）。",
      "分辨：ビール／ビル。"
    ],
  },
  "beg-3-1": {
    vocab: [
      { ja: "おはようございます", reading: "おはようございます", meaningZh: "早晨（禮貌）", romaji: "ohayō gozaimasu" },
      { ja: "こんにちは", reading: "こんにちは", meaningZh: "你好／午安", romaji: "konnichiwa" },
      { ja: "こんばんは", reading: "こんばんは", meaningZh: "晚安（見面）", romaji: "konbanwa" },
      { ja: "ありがとうございます", reading: "ありがとうございます", meaningZh: "多謝", romaji: "arigatō gozaimasu" },
      { ja: "すみません", reading: "すみません", meaningZh: "唔好意思／麻煩", romaji: "sumimasen" },
      { ja: "さようなら", reading: "さようなら", meaningZh: "再見", romaji: "sayōnara" }
    ],
    examples: [
      { ja: "おはようございます。", reading: "おはようございます。", meaningZh: "早晨。" },
      { ja: "ありがとうございます。", reading: "ありがとうございます。", meaningZh: "多謝。" }
    ],
    tipsZh: [
      "朝早用おはようございます；日間こんにちは；夜晚見面用こんばんは。",
      "すみません可以道歉，亦可以叫人注意／道謝。"
    ],
    practiceZh: [
      "跟讀每句三遍，注意音調。",
      "角色扮演：見面→問候→道謝→再見。",
      "錄低自己講一輪，對照範本。"
    ],
  },
  "beg-3-2": {
    vocab: [
      { ja: "わたし", reading: "わたし", meaningZh: "我", romaji: "watashi" },
      { ja: "です", reading: "です", meaningZh: "係（丁寧）", romaji: "desu" },
      { ja: "はじめまして", reading: "はじめまして", meaningZh: "初次見面", romaji: "hajimemashite" },
      { ja: "から来ました", reading: "からきました", meaningZh: "由…嚟", romaji: "kara kimashita" },
      { ja: "よろしくお願いします", reading: "よろしくおねがいします", meaningZh: "請多指教", romaji: "yoroshiku onegaishimasu" },
      { ja: "学生", reading: "がくせい", meaningZh: "學生", romaji: "gakusei" }
    ],
    examples: [
      { ja: "はじめまして。〇〇です。", reading: "はじめまして。まるまるです。", meaningZh: "初次見面，我係〇〇。" },
      { ja: "香港から来ました。", reading: "ほんこんからきました。", meaningZh: "我由香港嚟。" }
    ],
    tipsZh: [
      "「AはBです」＝A係B；否定用「ではありません／じゃありません」。",
      "自我介紹常見順序：打招呼→名→來自邊→請多指教。"
    ],
    practiceZh: [
      "寫一段自己介紹（3–5 句）。",
      "練習：です／ではありません 各造兩句。",
      "對住鏡講兩分鐘。"
    ],
  },
  "beg-4-1": {
    vocab: [
      { ja: "一", reading: "いち", meaningZh: "1", romaji: "ichi" },
      { ja: "二", reading: "に", meaningZh: "2", romaji: "ni" },
      { ja: "三", reading: "さん", meaningZh: "3", romaji: "san" },
      { ja: "四", reading: "よん／し", meaningZh: "4", romaji: "yon/shi" },
      { ja: "五", reading: "ご", meaningZh: "5", romaji: "go" },
      { ja: "十", reading: "じゅう", meaningZh: "10", romaji: "jū" },
      { ja: "百", reading: "ひゃく", meaningZh: "100", romaji: "hyaku" },
      { ja: "つ", reading: "つ", meaningZh: "個（通用量詞）", romaji: "tsu" },
      { ja: "人", reading: "にん／り", meaningZh: "人", romaji: "nin/ri" },
      { ja: "本", reading: "ほん", meaningZh: "長形物（支／本）", romaji: "hon" }
    ],
    examples: [
      { ja: "りんごが三つあります。", reading: "りんごがみっつあります。", meaningZh: "有三個蘋果。" },
      { ja: "学生が五人います。", reading: "がくせいがごにんいます。", meaningZh: "有五個學生。" }
    ],
    tipsZh: [
      "小數量常用「ひとつ・ふたつ・みっつ…」。",
      "人：一人（ひとり）、二人（ふたり）、三人起多數讀〜にん。"
    ],
    practiceZh: [
      "數到 100，重點練 4、7、9 嘅讀法。",
      "練習〜つ・〜人・〜本。",
      "聽數字聽寫十題。"
    ],
  },
  "beg-4-2": {
    vocab: [
      { ja: "時", reading: "じ", meaningZh: "點鐘", romaji: "ji" },
      { ja: "分", reading: "ふん／ぷん", meaningZh: "分鐘", romaji: "fun/pun" },
      { ja: "半", reading: "はん", meaningZh: "半", romaji: "han" },
      { ja: "今", reading: "いま", meaningZh: "而家", romaji: "ima" },
      { ja: "今日", reading: "きょう", meaningZh: "今日", romaji: "kyō" },
      { ja: "明日", reading: "あした", meaningZh: "聽日", romaji: "ashita" },
      { ja: "月曜日", reading: "げつようび", meaningZh: "星期一", romaji: "getsuyōbi" },
      { ja: "日曜日", reading: "にちようび", meaningZh: "星期日", romaji: "nichiyōbi" }
    ],
    examples: [
      { ja: "今は三時半です。", reading: "いまはさんじはんです。", meaningZh: "而家三點半。" },
      { ja: "明日は火曜日です。", reading: "あしたはかようびです。", meaningZh: "聽日係星期二。" }
    ],
    tipsZh: [
      "鐘點：〜時；半分：〜時半；分鐘留意促音／半濁音變化（一分＝いっぷん）。",
      "曜日：月火水木金土日＋ようび。"
    ],
    practiceZh: [
      "講出而家幾點。",
      "背齊七日曜日。",
      "造三句約時間（曜日＋時刻）。"
    ],
  },
  "beg-5-1": {
    vocab: [
      { ja: "は", reading: "は", meaningZh: "主題助詞（讀わ）", romaji: "wa" },
      { ja: "が", reading: "が", meaningZh: "主語／新資訊", romaji: "ga" },
      { ja: "を", reading: "を", meaningZh: "受詞助詞（讀お）", romaji: "o" },
      { ja: "私", reading: "わたし", meaningZh: "我", romaji: "watashi" },
      { ja: "水", reading: "みず", meaningZh: "水", romaji: "mizu" },
      { ja: "飲む", reading: "のむ", meaningZh: "飲", romaji: "nomu" }
    ],
    examples: [
      { ja: "わたしは水を飲みます。", reading: "わたしはみずをのみます。", meaningZh: "我飲水。" },
      { ja: "猫がいます。", reading: "ねこがいます。", meaningZh: "有隻貓。" }
    ],
    tipsZh: [
      "「は」標主題（呢句講緊邊個／邊樣）；「が」常標主語或新出現資訊。",
      "「を」標動作涉及嘅對象（受詞）。"
    ],
    practiceZh: [
      "抄五句：は／が／を。",
      "填空：わたし＿パン＿食べます。",
      "自己造三句。"
    ],
  },
  "beg-5-2": {
    vocab: [
      { ja: "に", reading: "に", meaningZh: "時間／目的地／存在位置", romaji: "ni" },
      { ja: "で", reading: "で", meaningZh: "動作發生場所／手段", romaji: "de" },
      { ja: "へ", reading: "へ", meaningZh: "移動方向（讀え）", romaji: "e" },
      { ja: "学校", reading: "がっこう", meaningZh: "學校", romaji: "gakkō" },
      { ja: "行く", reading: "いく", meaningZh: "去", romaji: "iku" },
      { ja: "家", reading: "いえ／うち", meaningZh: "屋企", romaji: "ie/uchi" }
    ],
    examples: [
      { ja: "学校へ行きます。", reading: "がっこうへいきます。", meaningZh: "去學校。" },
      { ja: "図書館で勉強します。", reading: "としょかんでべんきょうします。", meaningZh: "喺圖書館溫習。" }
    ],
    tipsZh: [
      "移動去邊：へ／に；喺某處做嘢用で。",
      "時間點多用に：三時に会います。"
    ],
    practiceZh: [
      "分辨に／で：造兩組對比句。",
      "畫簡單場景再造句。",
      "口頭複述三句。"
    ],
  },
  "beg-6-1": {
    vocab: [
      { ja: "あります", reading: "あります", meaningZh: "有（無生命）", romaji: "arimasu" },
      { ja: "います", reading: "います", meaningZh: "有（有生命）", romaji: "imasu" },
      { ja: "机", reading: "つくえ", meaningZh: "書枱", romaji: "tsukue" },
      { ja: "本", reading: "ほん", meaningZh: "書", romaji: "hon" },
      { ja: "上", reading: "うえ", meaningZh: "上面", romaji: "ue" },
      { ja: "人", reading: "ひと", meaningZh: "人", romaji: "hito" }
    ],
    examples: [
      { ja: "机の上に本があります。", reading: "つくえのうえにほんがあります。", meaningZh: "桌上有本書。" },
      { ja: "部屋に猫がいます。", reading: "へやにねこがいます。", meaningZh: "房裏有隻貓。" }
    ],
    tipsZh: [
      "無生命（書、枱、建築物）用あります；人／動物用います。",
      "存在句常配「場所に＋が＋あります／います」。"
    ],
    practiceZh: [
      "分類十個詞：あります定います。",
      "描述房間三樣嘢。",
      "聽句判斷用邊個動詞。"
    ],
  },
  "beg-6-2": {
    vocab: [
      { ja: "大きい", reading: "おおきい", meaningZh: "大", romaji: "ōkii" },
      { ja: "小さい", reading: "ちいさい", meaningZh: "細", romaji: "chiisai" },
      { ja: "広い", reading: "ひろい", meaningZh: "闊", romaji: "hiroi" },
      { ja: "きれい", reading: "きれい", meaningZh: "靚／乾淨（な形）", romaji: "kirei" },
      { ja: "静か", reading: "しずか", meaningZh: "靜（な形）", romaji: "shizuka" },
      { ja: "部屋", reading: "へや", meaningZh: "房間", romaji: "heya" }
    ],
    examples: [
      { ja: "この部屋は広いです。", reading: "このへやはひろいです。", meaningZh: "呢間房好闊。" },
      { ja: "公園は静かです。", reading: "こうえんはしずかです。", meaningZh: "公園好靜。" }
    ],
    tipsZh: [
      "い形容詞以い結尾（大きい）；な形容詞接名詞前加な（きれいな部屋）。",
      "作謂語時兩者都可以＋です。"
    ],
    practiceZh: [
      "列十個形容詞（い／な分開）。",
      "造肯定同否定各兩句。",
      "用三個形容詞描述朋友。"
    ],
  },
  "beg-7-1": {
    vocab: [
      { ja: "食べます", reading: "たべます", meaningZh: "食", romaji: "tabemasu" },
      { ja: "飲みます", reading: "のみます", meaningZh: "飲", romaji: "nomimasu" },
      { ja: "見ます", reading: "みます", meaningZh: "睇", romaji: "mimasu" },
      { ja: "します", reading: "します", meaningZh: "做", romaji: "shimasu" },
      { ja: "ました", reading: "ました", meaningZh: "過去丁寧", romaji: "mashita" },
      { ja: "ません", reading: "ません", meaningZh: "否定丁寧", romaji: "masen" },
      { ja: "昨日", reading: "きのう", meaningZh: "尋日", romaji: "kinō" },
      { ja: "映画", reading: "えいが", meaningZh: "電影", romaji: "eiga" }
    ],
    examples: [
      { ja: "昨日映画を見ました。", reading: "きのうえいがをみました。", meaningZh: "尋日睇咗戲。" },
      { ja: "朝ごはんを食べません。", reading: "あさごはんをたべません。", meaningZh: "唔食早餐。" }
    ],
    tipsZh: [
      "丁寧形：ます（現在／將來）、ません（否定）、ました（過去）、ませんでした（過去否定）。",
      "詞典形（食べる）入門之後再系統學；而家先熟口語禮貌形。"
    ],
    practiceZh: [
      "將 15 個動詞變成ます／ません／ました。",
      "寫三日行程（朝／晝／夜）。",
      "用問答：何をしましたか。"
    ],
  },
  "beg-7-2": {
    vocab: [
      { ja: "たい", reading: "たい", meaningZh: "想…", romaji: "tai" },
      { ja: "行きたい", reading: "いきたい", meaningZh: "想去", romaji: "ikitai" },
      { ja: "食べたい", reading: "たべたい", meaningZh: "想食", romaji: "tabetai" },
      { ja: "日本", reading: "にほん", meaningZh: "日本", romaji: "nihon" },
      { ja: "寿司", reading: "すし", meaningZh: "壽司", romaji: "sushi" }
    ],
    examples: [
      { ja: "日本へ行きたいです。", reading: "にほんへいきたいです。", meaningZh: "想去日本。" },
      { ja: "寿司を食べたいです。", reading: "すしをたべたいです。", meaningZh: "想食壽司。" }
    ],
    tipsZh: [
      "動詞ます形去掉ます＋たい：行きます→行きたい。",
      "たい活用似い形容詞：たくないです＝唔想。"
    ],
    practiceZh: [
      "造五句〜たいです。",
      "角色扮演：餐廳想食咩。",
      "聽句捉有冇「たい」。"
    ],
  },
  "beg-8-1": {
    vocab: [
      { ja: "私", reading: "わたし", meaningZh: "我", romaji: "watashi" },
      { ja: "名前", reading: "なまえ", meaningZh: "名", romaji: "namae" },
      { ja: "友達", reading: "ともだち", meaningZh: "朋友", romaji: "tomodachi" },
      { ja: "好き", reading: "すき", meaningZh: "鍾意", romaji: "suki" },
      { ja: "毎日", reading: "まいにち", meaningZh: "每日", romaji: "mainichi" },
      { ja: "勉強", reading: "べんきょう", meaningZh: "溫習／學習", romaji: "benkyō" }
    ],
    examples: [
      { ja: "私の名前は太郎です。", reading: "わたしのなまえはたろうです。", meaningZh: "我名叫太郎。" },
      { ja: "毎日日本語を勉強します。", reading: "まいにちにほんごをべんきょうします。", meaningZh: "每日學日文。" }
    ],
    tipsZh: [
      "綜合課重點：假名讀寫＋です／ます＋助詞一齊用。",
      "讀短文時先標讀法，再譯意思。"
    ],
    practiceZh: [
      "讀一段短文，標出全部讀法。",
      "譯成粵語／中文。",
      "默寫自我介紹。"
    ],
  },
  "beg-8-2": {
    vocab: [
      { ja: "問題", reading: "もんだい", meaningZh: "問題", romaji: "mondai" },
      { ja: "答え", reading: "こたえ", meaningZh: "答案", romaji: "kotae" },
      { ja: "正解", reading: "せいかい", meaningZh: "正確答案", romaji: "seikai" },
      { ja: "復習", reading: "ふくしゅう", meaningZh: "溫習", romaji: "fukushū" },
      { ja: "試験", reading: "しけん", meaningZh: "考試", romaji: "shiken" },
      { ja: "準備", reading: "じゅんび", meaningZh: "準備", romaji: "junbi" }
    ],
    examples: [
      { ja: "試験の準備をします。", reading: "しけんのじゅんびをします。", meaningZh: "準備考試。" },
      { ja: "答えを書いてください。", reading: "こたえをかいてください。", meaningZh: "請寫答案。" }
    ],
    tipsZh: [
      "過關測驗唔使完美；錯題先係之後 N5 嘅起點。",
      "建議將弱項（假名／助詞／ます形）分開再練。"
    ],
    practiceZh: [
      "完成 20 題小測（自製都得）。",
      "錯題重溫並造句。",
      "訂一個 N5 學習目標。"
    ],
  },
  "n5-1-1": {
    vocab: [
      { ja: "家族", reading: "かぞく", meaningZh: "家人" },
      { ja: "父", reading: "ちち", meaningZh: "爸爸（自己）" },
      { ja: "母", reading: "はは", meaningZh: "媽媽（自己）" },
      { ja: "兄", reading: "あに", meaningZh: "哥哥（自己）" },
      { ja: "姉", reading: "あね", meaningZh: "家姐（自己）" },
      { ja: "弟", reading: "おとうと", meaningZh: "細佬" },
      { ja: "妹", reading: "いもうと", meaningZh: "細妹" },
      { ja: "子供", reading: "こども", meaningZh: "細路" }
    ],
    examples: [
      { ja: "兄は学生です。", reading: "あにはがくせいです。", meaningZh: "哥哥係學生。" },
      { ja: "家族は四人です。", reading: "かぞくはよにんです。", meaningZh: "一家四口。" }
    ],
    tipsZh: [
      "講自己家人用父・母・兄・姉；講對方家人多用お父さん等禮貌形。",
      "讀法要記音讀／訓讀差異：人（ひと／にん）。"
    ],
    practiceZh: [
      "背 20 個家族詞並寫讀法。",
      "畫家族樹，用日文介紹。",
      "聽詞配對圖像。"
    ],
  },
  "n5-1-2": {
    vocab: [
      { ja: "起きる", reading: "おきる", meaningZh: "起身" },
      { ja: "寝る", reading: "ねる", meaningZh: "瞓" },
      { ja: "行く", reading: "いく", meaningZh: "去" },
      { ja: "来る", reading: "くる", meaningZh: "嚟" },
      { ja: "働く", reading: "はたらく", meaningZh: "返工" },
      { ja: "朝", reading: "あさ", meaningZh: "朝早" },
      { ja: "夜", reading: "よる", meaningZh: "夜晚" }
    ],
    examples: [
      { ja: "朝七時に起きます。", reading: "あさしちじにおきます。", meaningZh: "朝早七點起身。" },
      { ja: "夜十時に寝ます。", reading: "よるじゅうじにねます。", meaningZh: "夜晚十點瞓。" }
    ],
    tipsZh: [
      "一日行程：時間に＋動詞ます形。",
      "順序詞：まず（首先）、それから（之後）、最後に。"
    ],
    practiceZh: [
      "寫自己時間表（5 句）。",
      "口頭講三次。",
      "錄音自評流暢度。"
    ],
  },
  "n5-2-1": {
    vocab: [
      { ja: "て形", reading: "てけい", meaningZh: "て形" },
      { ja: "待つ", reading: "まつ", meaningZh: "等" },
      { ja: "書く", reading: "かく", meaningZh: "寫" },
      { ja: "読む", reading: "よむ", meaningZh: "讀" },
      { ja: "する", reading: "する", meaningZh: "做" },
      { ja: "来る", reading: "くる", meaningZh: "嚟" },
      { ja: "ください", reading: "ください", meaningZh: "請…" }
    ],
    examples: [
      { ja: "ちょっと待ってください。", reading: "ちょっとまってください。", meaningZh: "請等一陣。" },
      { ja: "名前を書いてください。", reading: "なまえをかいてください。", meaningZh: "請寫名。" }
    ],
    tipsZh: [
      "グループI：う段→って／いて／いで 等；グループII：る→て；する→して、来る→来て。",
      "てください＝請你做…（請求）。"
    ],
    practiceZh: [
      "完成て形變化表 15 個。",
      "造五句てください。",
      "聽寫て形。"
    ],
  },
  "n5-2-2": {
    vocab: [
      { ja: "ています", reading: "ています", meaningZh: "進行／狀態" },
      { ja: "今", reading: "いま", meaningZh: "而家" },
      { ja: "住む", reading: "すむ", meaningZh: "住" },
      { ja: "知る", reading: "しる", meaningZh: "知（知っている）" },
      { ja: "結婚", reading: "けっこん", meaningZh: "結婚" }
    ],
    examples: [
      { ja: "今、ご飯を食べています。", reading: "いま、ごはんをたべています。", meaningZh: "而家食緊飯。" },
      { ja: "東京に住んでいます。", reading: "とうきょうにすんでいます。", meaningZh: "住喺東京。" }
    ],
    tipsZh: [
      "て＋います：①進行中 ②習慣 ③結果狀態（住んでいる、知っている）。",
      "知ります少用嚟講「識」；多數講知っている。"
    ],
    practiceZh: [
      "分辨進行／習慣各兩句。",
      "描述而家做緊咩。",
      "看圖造句。"
    ],
  },
  "n5-3-1": {
    vocab: [
      { ja: "駅", reading: "えき", meaningZh: "車站" },
      { ja: "コンビニ", reading: "コンビニ", meaningZh: "便利店" },
      { ja: "前", reading: "まえ", meaningZh: "前面" },
      { ja: "後ろ", reading: "うしろ", meaningZh: "後面" },
      { ja: "右", reading: "みぎ", meaningZh: "右" },
      { ja: "左", reading: "ひだり", meaningZh: "左" },
      { ja: "近く", reading: "ちかく", meaningZh: "附近" }
    ],
    examples: [
      { ja: "駅の前にコンビニがあります。", reading: "えきのまえにコンビニがあります。", meaningZh: "車站前面有便利店。" },
      { ja: "右に曲がってください。", reading: "みぎにまがってください。", meaningZh: "請轉右。" }
    ],
    tipsZh: [
      "場所の＋位置詞：の前／の後ろ／の右。",
      "問路常用：〜はどこですか／まっすぐ行ってください。"
    ],
    practiceZh: [
      "背場所詞＋讀法。",
      "用地圖指路三段。",
      "聽對話搵地點。"
    ],
  },
  "n5-3-2": {
    vocab: [
      { ja: "電車", reading: "でんしゃ", meaningZh: "電車" },
      { ja: "バス", reading: "バス", meaningZh: "巴士" },
      { ja: "徒歩", reading: "とほ", meaningZh: "步行" },
      { ja: "自転車", reading: "じてんしゃ", meaningZh: "單車" },
      { ja: "乗る", reading: "のる", meaningZh: "搭乘" },
      { ja: "降りる", reading: "おりる", meaningZh: "落車" }
    ],
    examples: [
      { ja: "電車で行きます。", reading: "でんしゃでいきます。", meaningZh: "搭電車去。" },
      { ja: "次で降ります。", reading: "つぎでおります。", meaningZh: "下一站落車。" }
    ],
    tipsZh: [
      "交通手段用助詞で：バスで、歩いて（例外用て形）。",
      "乗る／降りる：乗り物に乗る、駅で降りる。"
    ],
    practiceZh: [
      "聽交通公告關鍵詞。",
      "計劃假日路線兩句。",
      "造句用で。"
    ],
  },
  "n5-4-1": {
    vocab: [
      { ja: "食べ物", reading: "たべもの", meaningZh: "食物" },
      { ja: "飲み物", reading: "のみもの", meaningZh: "飲品" },
      { ja: "肉", reading: "にく", meaningZh: "肉" },
      { ja: "魚", reading: "さかな", meaningZh: "魚" },
      { ja: "野菜", reading: "やさい", meaningZh: "菜" },
      { ja: "甘い", reading: "あまい", meaningZh: "甜" },
      { ja: "辛い", reading: "からい", meaningZh: "辣" },
      { ja: "ください", reading: "ください", meaningZh: "請畀…" }
    ],
    examples: [
      { ja: "ラーメンを一つください。", reading: "ラーメンをひとつください。", meaningZh: "請畀一碗拉麵。" },
      { ja: "この料理は辛いです。", reading: "このりょうりはからいです。", meaningZh: "呢道菜好辣。" }
    ],
    tipsZh: [
      "點餐：〜をください／〜をお願いします。",
      "味道：甘い・辛い・苦い・酸っぱい・おいしい。"
    ],
    practiceZh: [
      "分類食物卡並寫讀法。",
      "描述喜好三句。",
      "角色扮演點餐。"
    ],
  },
  "n5-4-2": {
    vocab: [
      { ja: "メニュー", reading: "メニュー", meaningZh: "餐牌" },
      { ja: "注文", reading: "ちゅうもん", meaningZh: "點餐" },
      { ja: "お会計", reading: "おかいけい", meaningZh: "埋單" },
      { ja: "別々", reading: "べつべつ", meaningZh: "分開付" },
      { ja: "おすすめ", reading: "おすすめ", meaningZh: "推介" },
      { ja: "水", reading: "みず", meaningZh: "水" }
    ],
    examples: [
      { ja: "すみません、メニューをください。", reading: "すみません、メニューをください。", meaningZh: "唔好意思，請畀餐牌。" },
      { ja: "お会計お願いします。", reading: "おかいけいおねがいします。", meaningZh: "麻煩埋單。" }
    ],
    tipsZh: [
      "叫店員：すみません；結帳：お会計お願いします。",
      "分開付：別々でお願いします。"
    ],
    practiceZh: [
      "背五句店員／客人用語。",
      "雙人對話一分鐘。",
      "聽對話捉關鍵句。"
    ],
  },
  "n5-5-1": {
    vocab: [
      { ja: "人", reading: "ひと／じん", meaningZh: "人" },
      { ja: "日", reading: "ひ／にち", meaningZh: "日／日子" },
      { ja: "月", reading: "つき／げつ", meaningZh: "月" },
      { ja: "水", reading: "みず／すい", meaningZh: "水" },
      { ja: "火", reading: "ひ／か", meaningZh: "火" },
      { ja: "木", reading: "き／もく", meaningZh: "木" },
      { ja: "金", reading: "かね／きん", meaningZh: "金／錢" },
      { ja: "土", reading: "つち／ど", meaningZh: "土" }
    ],
    examples: [
      { ja: "日曜日に水を飲みます。", reading: "にちようびにみずをのみます。", meaningZh: "星期日飲水。" },
      { ja: "日本人です。", reading: "にほんじんです。", meaningZh: "係日本人。" }
    ],
    tipsZh: [
      "N5 漢字多數有訓讀（kun）同音讀（on）：水＝みず／スイ。",
      "曜日漢字：日月火水木金土。"
    ],
    practiceZh: [
      "寫筆順並標讀法。",
      "音訓各讀兩次。",
      "組詞：水・水曜日。"
    ],
  },
  "n5-5-2": {
    vocab: [
      { ja: "上", reading: "うえ／じょう", meaningZh: "上" },
      { ja: "下", reading: "した／か", meaningZh: "下" },
      { ja: "左", reading: "ひだり／さ", meaningZh: "左" },
      { ja: "右", reading: "みぎ／う", meaningZh: "右" },
      { ja: "大", reading: "おお／だい", meaningZh: "大" },
      { ja: "小", reading: "ちい／しょう", meaningZh: "小" },
      { ja: "中", reading: "なか／ちゅう", meaningZh: "中" }
    ],
    examples: [
      { ja: "本は机の上です。", reading: "ほんはつくえのうえです。", meaningZh: "書喺枱上面。" },
      { ja: "大きい犬と小さい猫", reading: "おおきいいぬとちいさいねこ", meaningZh: "大狗同細貓" }
    ],
    tipsZh: [
      "方位漢字好常同の一齊：の上、の下。",
      "大小：大きい／小さい（訓）同大學（だいがく）音讀。"
    ],
    practiceZh: [
      "默寫 15 字＋讀法。",
      "看圖選漢字。",
      "短句填空。"
    ],
  },
  "n5-6-1": {
    vocab: [
      { ja: "寒い", reading: "さむい", meaningZh: "凍" },
      { ja: "暑い", reading: "あつい", meaningZh: "熱（天氣）" },
      { ja: "高い", reading: "たかい", meaningZh: "高／貴" },
      { ja: "安い", reading: "やすい", meaningZh: "平" },
      { ja: "くない", reading: "くない", meaningZh: "い形否定" },
      { ja: "かった", reading: "かった", meaningZh: "い形過去" }
    ],
    examples: [
      { ja: "昨日は寒かったです。", reading: "きのうはさむかったです。", meaningZh: "尋日好凍。" },
      { ja: "今日は暑くないです。", reading: "きょうはあつくないです。", meaningZh: "今日唔熱。" }
    ],
    tipsZh: [
      "い形容詞：去掉い＋くない／かった／くなかった。",
      "丁寧形可加です：寒かったです。"
    ],
    practiceZh: [
      "變化練習十個い形容詞。",
      "寫天氣日記三句。",
      "聽力判斷時態。"
    ],
  },
  "n5-6-2": {
    vocab: [
      { ja: "静か", reading: "しずか", meaningZh: "靜" },
      { ja: "元気", reading: "げんき", meaningZh: "精神／健康" },
      { ja: "便利", reading: "べんり", meaningZh: "方便" },
      { ja: "有名", reading: "ゆうめい", meaningZh: "有名" },
      { ja: "じゃありません", reading: "じゃありません", meaningZh: "な形否定" }
    ],
    examples: [
      { ja: "この町は静かです。", reading: "このまちはしずかです。", meaningZh: "呢個鎮好靜。" },
      { ja: "便利じゃありません。", reading: "べんりじゃありません。", meaningZh: "唔方便。" }
    ],
    tipsZh: [
      "な形容詞：名詞前＋な；謂語＋です／でした／じゃありません。",
      "唔好寫成「静かい」——唔係い形容詞。"
    ],
    practiceZh: [
      "造句比較い／な。",
      "描述房間三句。",
      "小測變化。"
    ],
  },
  "n5-7-1": {
    vocab: [
      { ja: "より", reading: "より", meaningZh: "比起…" },
      { ja: "のほうが", reading: "のほうが", meaningZh: "…嗰邊更" },
      { ja: "一番", reading: "いちばん", meaningZh: "最" },
      { ja: "同じ", reading: "おなじ", meaningZh: "一樣" }
    ],
    examples: [
      { ja: "電車よりバスのほうが安いです。", reading: "でんしゃよりバスのほうがやすいです。", meaningZh: "巴士平過電車。" },
      { ja: "夏が一番好きです。", reading: "なつがいちばんすきです。", meaningZh: "最鍾意夏天。" }
    ],
    tipsZh: [
      "AよりBのほうが〜：B 比 A 更〜。",
      "最高級：いちばん＋形容詞。"
    ],
    practiceZh: [
      "造三組比較。",
      "討論飲食喜好。",
      "讀短文搵比較句。"
    ],
  },
  "n5-7-2": {
    vocab: [
      { ja: "ほしい", reading: "ほしい", meaningZh: "想要（物件）" },
      { ja: "たい", reading: "たい", meaningZh: "想做（動詞）" },
      { ja: "欲しいです", reading: "ほしいです", meaningZh: "想要" },
      { ja: "時間がほしい", reading: "じかんがほしい", meaningZh: "想要時間" }
    ],
    examples: [
      { ja: "新しい鞄がほしいです。", reading: "あたらしいかばんがほしいです。", meaningZh: "想要新袋。" },
      { ja: "休みたいです。", reading: "やすみたいです。", meaningZh: "想休息。" }
    ],
    tipsZh: [
      "ほしい標物件（がほしい）；たい由動詞變嚟（食べたい）。",
      "第三人稱常用ほしがっています／たがっています。"
    ],
    practiceZh: [
      "分辨ほしい／たい各三句。",
      "寫願望清單。",
      "口頭分享一分鐘。"
    ],
  },
  "n5-8-1": {
    vocab: [
      { ja: "から", reading: "から", meaningZh: "由／因為" },
      { ja: "まで", reading: "まで", meaningZh: "到" },
      { ja: "ごろ", reading: "ごろ", meaningZh: "大約" },
      { ja: "時", reading: "じ", meaningZh: "點" },
      { ja: "働く", reading: "はたらく", meaningZh: "返工" }
    ],
    examples: [
      { ja: "九時から五時まで働きます。", reading: "くじからごじまではたらきます。", meaningZh: "由九點做到五點。" },
      { ja: "三時ごろ会いましょう。", reading: "さんじごろあいましょう。", meaningZh: "大約三點見啦。" }
    ],
    tipsZh: [
      "時間範圍：から〜まで；大約時刻：〜ごろ（唔好用喺分數太精確場合）。",
      "から亦可表原因：雨だから行きません。"
    ],
    practiceZh: [
      "填時間表。",
      "約朋友對話。",
      "聽力捉時間。"
    ],
  },
  "n5-8-2": {
    vocab: [
      { ja: "いつも", reading: "いつも", meaningZh: "成日" },
      { ja: "よく", reading: "よく", meaningZh: "經常" },
      { ja: "ときどき", reading: "ときどき", meaningZh: "有時" },
      { ja: "あまり", reading: "あまり", meaningZh: "唔係幾（＋否定）" },
      { ja: "ぜんぜん", reading: "ぜんぜん", meaningZh: "完全（＋否定）" }
    ],
    examples: [
      { ja: "いつもコーヒーを飲みます。", reading: "いつもコーヒーをのみます。", meaningZh: "成日飲咖啡。" },
      { ja: "あまり食べません。", reading: "あまりたべません。", meaningZh: "唔係幾食。" }
    ],
    tipsZh: [
      "頻度由高到低：いつも→よく→ときどき→たまに。",
      "あまり／ぜんぜん 通常配否定形。"
    ],
    practiceZh: [
      "造句用每個頻度詞。",
      "做自我調查問卷。",
      "同伴互相訪問。"
    ],
  },
  "n5-9-1": {
    vocab: [
      { ja: "お知らせ", reading: "おしらせ", meaningZh: "通告" },
      { ja: "メモ", reading: "メモ", meaningZh: "便條" },
      { ja: "営業", reading: "えいぎょう", meaningZh: "營業" },
      { ja: "休み", reading: "やすみ", meaningZh: "休息／放假" },
      { ja: "注意", reading: "ちゅうい", meaningZh: "注意" }
    ],
    examples: [
      { ja: "本日は休みです。", reading: "ほんじつはやすみです。", meaningZh: "今日休息。" },
      { ja: "ドアにご注意ください。", reading: "ドアにごちゅういください。", meaningZh: "請小心門。" }
    ],
    tipsZh: [
      "告示好短，先搵日付・時間・禁止／依頼。",
      "ご〜ください係禮貌請求。"
    ],
    practiceZh: [
      "劃出生詞並寫讀法。",
      "答兩條理解題。",
      "改寫一則便條。"
    ],
  },
  "n5-9-2": {
    vocab: [
      { ja: "会話", reading: "かいわ", meaningZh: "對話" },
      { ja: "質問", reading: "しつもん", meaningZh: "問題" },
      { ja: "返事", reading: "へんじ", meaningZh: "回應" },
      { ja: "もう一度", reading: "もういちど", meaningZh: "再一次" },
      { ja: "ゆっくり", reading: "ゆっくり", meaningZh: "慢慢" }
    ],
    examples: [
      { ja: "もう一度お願いします。", reading: "もういちどおねがいします。", meaningZh: "請再說一次。" },
      { ja: "ゆっくり話してください。", reading: "ゆっくりはなしてください。", meaningZh: "請講慢啲。" }
    ],
    tipsZh: [
      "聽力先睇選項關鍵詞，再聽誰・何時・何處。",
      "聽唔清可以用「もう一度」「ゆっくり」求助。"
    ],
    practiceZh: [
      "聽兩次答題。",
      "對腳本核對。",
      "跟讀對話。"
    ],
  },
  "n5-10-1": {
    vocab: [
      { ja: "文法", reading: "ぶんぽう", meaningZh: "文法" },
      { ja: "漢字", reading: "かんじ", meaningZh: "漢字" },
      { ja: "復習", reading: "ふくしゅう", meaningZh: "溫習" },
      { ja: "弱点", reading: "じゃくてん", meaningZh: "弱項" },
      { ja: "練習", reading: "れんしゅう", meaningZh: "練習" }
    ],
    examples: [
      { ja: "文法を復習します。", reading: "ぶんぽうをふくしゅうします。", meaningZh: "溫習文法。" },
      { ja: "漢字の読み方を覚えます。", reading: "かんじのよみかたをおぼえます。", meaningZh: "記漢字讀法。" }
    ],
    tipsZh: [
      "綜合練習要同時睇讀法同意思，唔好淨係認樣。",
      "錯題本：寫「正解＋讀法＋自己造句」。"
    ],
    practiceZh: [
      "完成模擬 30 題。",
      "整理錯題本。",
      "重溫最弱單元。"
    ],
  },
  "n5-10-2": {
    vocab: [
      { ja: "模擬試験", reading: "もぎしけん", meaningZh: "模擬試" },
      { ja: "時間", reading: "じかん", meaningZh: "時間" },
      { ja: "点", reading: "てん", meaningZh: "分數" },
      { ja: "合格", reading: "ごうかく", meaningZh: "合格" },
      { ja: "次", reading: "つぎ", meaningZh: "下一個" }
    ],
    examples: [
      { ja: "模擬試験を受けます。", reading: "もぎしけんをうけます。", meaningZh: "考模擬試。" },
      { ja: "合格したいです。", reading: "ごうかくしたいです。", meaningZh: "想合格。" }
    ],
    tipsZh: [
      "模擬要計時；讀解先掃問題再讀文。",
      "考完分析：詞彙／文法／讀解／聽力邊部分最低。"
    ],
    practiceZh: [
      "嚴格計時完成。",
      "計分並寫弱項。",
      "訂 N4 計劃三點。"
    ],
  },
  "n4-1-1": {
    vocab: [
      { ja: "可能形", reading: "かのうけい", meaningZh: "可能形" },
      { ja: "読める", reading: "よめる", meaningZh: "識讀" },
      { ja: "話せる", reading: "はなせる", meaningZh: "識講" },
      { ja: "泳げる", reading: "およげる", meaningZh: "識游水" },
      { ja: "できる", reading: "できる", meaningZh: "識／可以（する）" }
    ],
    examples: [
      { ja: "漢字が読めます。", reading: "かんじがよめます。", meaningZh: "識讀漢字。" },
      { ja: "日本語が話せます。", reading: "にほんごがはなせます。", meaningZh: "識講日文。" }
    ],
    tipsZh: [
      "可能形多數用が標對象：漢字が読めます。",
      "グループI：書く→書ける；II：食べる→食べられる；する→できる、来る→来られる。"
    ],
    practiceZh: [
      "變化 20 動詞。",
      "能力自評表五項。",
      "對話：何ができますか。"
    ],
  },
  "n4-1-2": {
    vocab: [
      { ja: "意向形", reading: "いこうけい", meaningZh: "意向形" },
      { ja: "行こう", reading: "いこう", meaningZh: "不如去啦" },
      { ja: "食べよう", reading: "たべよう", meaningZh: "不如食啦" },
      { ja: "しよう", reading: "しよう", meaningZh: "不如做啦" }
    ],
    examples: [
      { ja: "週末に映画を見よう。", reading: "しゅうまつにえいがをみよう。", meaningZh: "週末不如睇戲啦。" },
      { ja: "一緒に勉強しましょう。", reading: "いっしょにべんきょうしましょう。", meaningZh: "一齊溫習啦。（丁寧）" }
    ],
    tipsZh: [
      "意向形：提議／打算。丁寧版用ましょう。",
      "う／よう 變化：書く→書こう、食べる→食べよう。"
    ],
    practiceZh: [
      "造五句提議。",
      "計劃週末對話。",
      "聽力捉意向形。"
    ],
  },
  "n4-2-1": {
    vocab: [
      { ja: "あげる", reading: "あげる", meaningZh: "畀人（自己→對方）" },
      { ja: "もらう", reading: "もらう", meaningZh: "由人收到" },
      { ja: "くれる", reading: "くれる", meaningZh: "人畀我／我哋" },
      { ja: "友達", reading: "ともだち", meaningZh: "朋友" },
      { ja: "プレゼント", reading: "プレゼント", meaningZh: "禮物" }
    ],
    examples: [
      { ja: "友達が本をくれました。", reading: "ともだちがほんをくれました。", meaningZh: "朋友送咗書畀我。" },
      { ja: "母に花をあげました。", reading: "ははにはなをあげました。", meaningZh: "送咗花畀媽媽。" }
    ],
    tipsZh: [
      "視點好重要：くれる＝對方→我；あげる＝我→對方；もらう＝我收到。",
      "畫箭嘴：誰→誰，先揀動詞。"
    ],
    practiceZh: [
      "畫授受箭嘴圖。",
      "填空五題。",
      "用真實故事造句。"
    ],
  },
  "n4-2-2": {
    vocab: [
      { ja: "てあげる", reading: "てあげる", meaningZh: "幫人做" },
      { ja: "てもらう", reading: "てもらう", meaningZh: "請人幫自己" },
      { ja: "てくれる", reading: "てくれる", meaningZh: "人幫我做" },
      { ja: "助ける", reading: "たすける", meaningZh: "幫／救" }
    ],
    examples: [
      { ja: "友達に教えてもらいました。", reading: "ともだちにおしえてもらいました。", meaningZh: "請朋友教我。" },
      { ja: "母が手伝ってくれました。", reading: "ははがてつだってくれました。", meaningZh: "媽媽幫咗我。" }
    ],
    tipsZh: [
      "て形＋授受：強調「幫」嘅方向。",
      "感謝常用：〜てくれてありがとう。"
    ],
    practiceZh: [
      "角色扮演幫忙。",
      "寫一句感謝訊息。",
      "小測三題。"
    ],
  },
  "n4-3-1": {
    vocab: [
      { ja: "たら", reading: "たら", meaningZh: "如果／之後（條件）" },
      { ja: "と", reading: "と", meaningZh: "一…就（恆常）" },
      { ja: "ば", reading: "ば", meaningZh: "若果（假定）" },
      { ja: "雨", reading: "あめ", meaningZh: "雨" },
      { ja: "降る", reading: "ふる", meaningZh: "落（雨）" }
    ],
    examples: [
      { ja: "雨が降ったら、家にいます。", reading: "あめがふったら、いえにいます。", meaningZh: "落雨就留喺屋企。" },
      { ja: "春になると暖かくなります。", reading: "はるになるとあたたかくなります。", meaningZh: "一到春天就會暖。" }
    ],
    tipsZh: [
      "たら：具體／一次條件；と：自然結果；ば：較正式假定。",
      "初學可先熟たら，再對比と／ば。"
    ],
    practiceZh: [
      "整對照表。",
      "三情境各造句。",
      "改錯練習。"
    ],
  },
  "n4-3-2": {
    vocab: [
      { ja: "なら", reading: "なら", meaningZh: "若係…嘅話" },
      { ja: "おすすめ", reading: "おすすめ", meaningZh: "推介" },
      { ja: "いい", reading: "いい", meaningZh: "好" }
    ],
    examples: [
      { ja: "日本へ行くなら、春がいいです。", reading: "にほんへいくなら、はるがいいです。", meaningZh: "若去日本，春天最好。" },
      { ja: "疲れるなら、休んでください。", reading: "つかれるなら、やすんでください。", meaningZh: "若攰就休息啦。" }
    ],
    tipsZh: [
      "なら多用於接對方話題再建議。",
      "同たら唔完全互換：なら偏「若係你講嗰樣」。"
    ],
    practiceZh: [
      "用なら答問題五句。",
      "建議對話。",
      "聽力捉なら。"
    ],
  },
  "n4-4-1": {
    vocab: [
      { ja: "そうです", reading: "そうです", meaningZh: "看起來…（樣態）" },
      { ja: "降る", reading: "ふる", meaningZh: "落" },
      { ja: "おいしい", reading: "おいしい", meaningZh: "好味" },
      { ja: "元気", reading: "げんき", meaningZh: "精神" }
    ],
    examples: [
      { ja: "雨が降りそうです。", reading: "あめがふりそうです。", meaningZh: "好似快落雨。" },
      { ja: "このケーキはおいしそうです。", reading: "このケーキはおいしそうです。", meaningZh: "呢個蛋糕睇落好好味。" }
    ],
    tipsZh: [
      "樣態そう：動詞ます去ます＋そう；い形容詞去い＋そう（例外：いい→よさそう）。",
      "表示「睇樣／感覺快要」。"
    ],
    practiceZh: [
      "看圖說そう。",
      "天氣描述三句。",
      "分辨樣態／傳聞。"
    ],
  },
  "n4-4-2": {
    vocab: [
      { ja: "そうです", reading: "そうです", meaningZh: "聽說…（傳聞）" },
      { ja: "によると", reading: "によると", meaningZh: "根據…" },
      { ja: "ニュース", reading: "ニュース", meaningZh: "新聞" }
    ],
    examples: [
      { ja: "明日は雪だそうです。", reading: "あしたはゆきだそうです。", meaningZh: "聽講聽日落雪。" },
      { ja: "彼は学生だそうです。", reading: "かれはがくせいだそうです。", meaningZh: "聽講佢係學生。" }
    ],
    tipsZh: [
      "傳聞そう接普通形＋そうです。",
      "樣態睇樣；傳聞聽聞——形態同意思都要分。"
    ],
    practiceZh: [
      "新聞標題改寫傳聞。",
      "傳話遊戲。",
      "聽力判斷類型。"
    ],
  },
  "n4-5-1": {
    vocab: [
      { ja: "思う", reading: "おもう", meaningZh: "諗／覺得" },
      { ja: "言う", reading: "いう", meaningZh: "講" },
      { ja: "話す", reading: "はなす", meaningZh: "傾／講" },
      { ja: "聞く", reading: "きく", meaningZh: "聽／問" },
      { ja: "読む", reading: "よむ", meaningZh: "讀" }
    ],
    examples: [
      { ja: "そう思います。", reading: "そうおもいます。", meaningZh: "我覺得係噉。" },
      { ja: "日本語で話します。", reading: "にほんごではなします。", meaningZh: "用日文講。" }
    ],
    tipsZh: [
      "動詞漢字常有音訓：言（い／ゲン）、話（はな／ワ）。",
      "組詞：会話・伝言・意見。"
    ],
    practiceZh: [
      "音訓練習。",
      "組詞十個。",
      "短文填漢字。"
    ],
  },
  "n4-5-2": {
    vocab: [
      { ja: "駅", reading: "えき", meaningZh: "站" },
      { ja: "道", reading: "みち／どう", meaningZh: "路" },
      { ja: "橋", reading: "はし", meaningZh: "橋" },
      { ja: "交差点", reading: "こうさてん", meaningZh: "十字路口" },
      { ja: "地図", reading: "ちず", meaningZh: "地圖" }
    ],
    examples: [
      { ja: "橋を渡ります。", reading: "はしをわたります。", meaningZh: "過橋。" },
      { ja: "道に迷いました。", reading: "みちにまよいました。", meaningZh: "迷路咗。" }
    ],
    tipsZh: [
      "交通漢字：駅・道・橋・車・通。",
      "注意同音：橋／箸／端 都可讀はし——靠漢字同語境。"
    ],
    practiceZh: [
      "默寫＋讀法。",
      "看地圖標漢字。",
      "聽寫地名句。"
    ],
  },
  "n4-6-1": {
    vocab: [
      { ja: "丁寧語", reading: "ていねいご", meaningZh: "丁寧語" },
      { ja: "謙譲語", reading: "けんじょうご", meaningZh: "謙譲語" },
      { ja: "少々", reading: "しょうしょう", meaningZh: "稍微" },
      { ja: "お待ちください", reading: "おまちください", meaningZh: "請稍等" }
    ],
    examples: [
      { ja: "少々お待ちください。", reading: "しょうしょうおまちください。", meaningZh: "請稍等。" },
      { ja: "いただきます。", reading: "いただきます。", meaningZh: "我食喇／領受。" }
    ],
    tipsZh: [
      "です／ます係丁寧語基礎。",
      "謙譲：降低自己，如伺う・参る（入門先記套語）。"
    ],
    practiceZh: [
      "店員對話練習。",
      "電話禮儀三句。",
      "錄音自評。"
    ],
  },
  "n4-6-2": {
    vocab: [
      { ja: "尊敬語", reading: "そんけいご", meaningZh: "尊敬語" },
      { ja: "いらっしゃる", reading: "いらっしゃる", meaningZh: "去／嚟／喺（尊）" },
      { ja: "おっしゃる", reading: "おっしゃる", meaningZh: "講（尊）" },
      { ja: "召し上がる", reading: "めしあがる", meaningZh: "食／飲（尊）" }
    ],
    examples: [
      { ja: "先生はもういらっしゃいますか。", reading: "せんせいはもういらっしゃいますか。", meaningZh: "老師到咗未？" },
      { ja: "何とおっしゃいましたか。", reading: "なんとおっしゃいましたか。", meaningZh: "你話咩？（敬）" }
    ],
    tipsZh: [
      "尊敬語抬高對方動作。",
      "先記常用替代動詞，再學お〜になる。"
    ],
    practiceZh: [
      "整對照表（普通／尊敬）。",
      "改寫五句。",
      "角色扮演。"
    ],
  },
  "n4-7-1": {
    vocab: [
      { ja: "授業", reading: "じゅぎょう", meaningZh: "堂課" },
      { ja: "宿題", reading: "しゅくだい", meaningZh: "功課" },
      { ja: "試験", reading: "しけん", meaningZh: "考試" },
      { ja: "部活", reading: "ぶかつ", meaningZh: "社團" },
      { ja: "専攻", reading: "せんこう", meaningZh: "主修" }
    ],
    examples: [
      { ja: "宿題が多いです。", reading: "しゅくだいがおおいです。", meaningZh: "功課好多。" },
      { ja: "日本語を専攻しています。", reading: "にほんごをせんこうしています。", meaningZh: "主修日文。" }
    ],
    tipsZh: [
      "學校生活詞：授業・宿題・出席・欠席。",
      "讀法要熟音讀詞：宿題（シュクダイ）。"
    ],
    practiceZh: [
      "背詞＋讀法。",
      "描述一日校園。",
      "聽力配對。"
    ],
  },
  "n4-7-2": {
    vocab: [
      { ja: "アルバイト", reading: "アルバイト", meaningZh: "兼職" },
      { ja: "休む", reading: "やすむ", meaningZh: "休息／請假" },
      { ja: "シフト", reading: "シフト", meaningZh: "更期" },
      { ja: "交換", reading: "こうかん", meaningZh: "對調" }
    ],
    examples: [
      { ja: "明日休んでもいいですか。", reading: "あしたやすんでもいいですか。", meaningZh: "聽日可唔可以休息？" },
      { ja: "シフトを代わってもらえますか。", reading: "シフトをかわってもらえますか。", meaningZh: "可唔可以對調更？" }
    ],
    tipsZh: [
      "てもいいですか＝可唔可以…？",
      "請假要講日期＋理由＋道歉套語。"
    ],
    practiceZh: [
      "寫請假訊息。",
      "對話練習。",
      "改正無禮句。"
    ],
  },
  "n4-8-1": {
    vocab: [
      { ja: "受身", reading: "うけみ", meaningZh: "被動" },
      { ja: "食べられる", reading: "たべられる", meaningZh: "被食" },
      { ja: "言われる", reading: "いわれる", meaningZh: "被講" },
      { ja: "弟", reading: "おとうと", meaningZh: "細佬" }
    ],
    examples: [
      { ja: "弟にケーキを食べられました。", reading: "おとうとにケーキをたべられました。", meaningZh: "蛋糕俾細佬食咗。" },
      { ja: "先生に褒められました。", reading: "せんせいにほめられました。", meaningZh: "俾老師讚。" }
    ],
    tipsZh: [
      "被動：主語係受影響一方；動作發出者用に。",
      "間接被動常帶麻煩／受害語感。"
    ],
    practiceZh: [
      "變化練習。",
      "簡化新聞標題。",
      "造受害／受讚句。"
    ],
  },
  "n4-8-2": {
    vocab: [
      { ja: "使役", reading: "しえき", meaningZh: "使役" },
      { ja: "食べさせる", reading: "たべさせる", meaningZh: "令人食" },
      { ja: "行かせる", reading: "いかせる", meaningZh: "令人去" },
      { ja: "させる", reading: "させる", meaningZh: "令人做（する）" }
    ],
    examples: [
      { ja: "子供に野菜を食べさせます。", reading: "こどもにやさいをたべさせます。", meaningZh: "叫細路食菜。" },
      { ja: "弟を買いに行かせました。", reading: "おとうとをかいにいかせました。", meaningZh: "叫細佬去買嘢。" }
    ],
    tipsZh: [
      "使役：令人做某事；對象常に／を。",
      "父母／上司情境好常見。"
    ],
    practiceZh: [
      "變化表。",
      "父母／上司情境造句。",
      "小測。"
    ],
  },
  "n4-9-1": {
    vocab: [
      { ja: "メール", reading: "メール", meaningZh: "電郵" },
      { ja: "件名", reading: "けんめい", meaningZh: "主旨" },
      { ja: "添付", reading: "てんぷ", meaningZh: "附件" },
      { ja: "返信", reading: "へんしん", meaningZh: "回覆" },
      { ja: "お知らせ", reading: "おしらせ", meaningZh: "通告" }
    ],
    examples: [
      { ja: "メールを送りました。", reading: "メールをおくりました。", meaningZh: "寄咗電郵。" },
      { ja: "添付ファイルをご確認ください。", reading: "てんぷファイルをごかくにんください。", meaningZh: "請確認附件。" }
    ],
    tipsZh: [
      "實用文章先抓：誰寄、要你做咩、期限。",
      "ご確認ください係商務常用。"
    ],
    practiceZh: [
      "抓主旨。",
      "答理解題。",
      "抄生詞＋讀法。"
    ],
  },
  "n4-9-2": {
    vocab: [
      { ja: "聴解", reading: "ちょうかい", meaningZh: "聽解" },
      { ja: "キーワード", reading: "キーワード", meaningZh: "關鍵詞" },
      { ja: "選択肢", reading: "せんたくし", meaningZh: "選項" },
      { ja: "予習", reading: "よしゅう", meaningZh: "預習" }
    ],
    examples: [
      { ja: "先に選択肢を読みます。", reading: "さきにせんたくしをよみます。", meaningZh: "先讀選項。" },
      { ja: "キーワードをメモします。", reading: "キーワードをメモします。", meaningZh: "記低關鍵詞。" }
    ],
    tipsZh: [
      "策略：預讀選項→聽時驗證→排除干擾。",
      "數字、否定、轉折（でも）成日係陷阱。"
    ],
    practiceZh: [
      "練三題。",
      "記干擾項。",
      "跟讀正確答案句。"
    ],
  },
  "n4-10-1": {
    vocab: [
      { ja: "復習", reading: "ふくしゅう", meaningZh: "溫習" },
      { ja: "可能", reading: "かのう", meaningZh: "可能" },
      { ja: "授受", reading: "じゅじゅ", meaningZh: "授受" },
      { ja: "条件", reading: "じょうけん", meaningZh: "條件" }
    ],
    examples: [
      { ja: "弱点を復習します。", reading: "じゃくてんをふくしゅうします。", meaningZh: "溫習弱項。" },
      { ja: "条件表現を整理します。", reading: "じょうけんひょうげんをせいりします。", meaningZh: "整理條件表達。" }
    ],
    tipsZh: [
      "N4 高頻弱項：可能・授受・たら／と／ば・敬語入門。",
      "教人一次係最好嘅複習。"
    ],
    practiceZh: [
      "錯題重做。",
      "自製十題。",
      "講解一題畀朋友聽。"
    ],
  },
  "n4-10-2": {
    vocab: [
      { ja: "模擬試験", reading: "もぎしけん", meaningZh: "模擬試" },
      { ja: "得点", reading: "とくてん", meaningZh: "得分" },
      { ja: "分析", reading: "ぶんせき", meaningZh: "分析" },
      { ja: "目標", reading: "もくひょう", meaningZh: "目標" }
    ],
    examples: [
      { ja: "計時して試験を受けます。", reading: "けいじてしけんをうけます。", meaningZh: "計時考試。" },
      { ja: "次はN3を目指します。", reading: "つぎはエヌさんをめざします。", meaningZh: "之後以 N3 為目標。" }
    ],
    tipsZh: [
      "模擬後一定做分數分析，唔好只睇總分。",
      "訂 N3：每週文法＋漢字＋一篇讀解。"
    ],
    practiceZh: [
      "計時完成。",
      "分析分數。",
      "寫 N3 目標三點。"
    ],
  },
  "n3-1-1": {
    vocab: [
      { ja: "によって", reading: "によって", meaningZh: "靠／根據／因…而異" },
      { ja: "に対して", reading: "にたいして", meaningZh: "對於" },
      { ja: "努力", reading: "どりょく", meaningZh: "努力" },
      { ja: "成功", reading: "せいこう", meaningZh: "成功" }
    ],
    examples: [
      { ja: "努力によって成功した。", reading: "どりょくによってせいこうした。", meaningZh: "靠努力成功咗。" },
      { ja: "質問に対して答える。", reading: "しつもんにたいしてこたえる。", meaningZh: "針對問題回答。" }
    ],
    tipsZh: [
      "によって：手段／依據／視乎…；に対して：對向對象。",
      "讀新聞時呢啲助詞短語好常見。"
    ],
    practiceZh: [
      "抄例句並標讀法。",
      "新聞句改寫。",
      "填空五題。"
    ],
  },
  "n3-1-2": {
    vocab: [
      { ja: "一方", reading: "いっぽう", meaningZh: "另一方面" },
      { ja: "反面", reading: "はんめん", meaningZh: "相反一面" },
      { ja: "その上", reading: "そのうえ", meaningZh: "而且" },
      { ja: "しかし", reading: "しかし", meaningZh: "但係" }
    ],
    examples: [
      { ja: "便利な一方、高い。", reading: "べんりないっぽう、たかい。", meaningZh: "方便但係貴。" },
      { ja: "安い。その上、おいしい。", reading: "やすい。そのうえ、おいしい。", meaningZh: "平，而且好味。" }
    ],
    tipsZh: [
      "接続詞決定段落邏輯：對比／添加／因果。",
      "一方・反面偏書面。"
    ],
    practiceZh: [
      "文章填接續。",
      "寫短段落。",
      "閱讀理解。"
    ],
  },
  "n3-2-1": {
    vocab: [
      { ja: "だろう", reading: "だろう", meaningZh: "大概（普通）" },
      { ja: "でしょう", reading: "でしょう", meaningZh: "大概（丁寧）" },
      { ja: "晴れ", reading: "はれ", meaningZh: "晴" },
      { ja: "思う", reading: "おもう", meaningZh: "覺得" }
    ],
    examples: [
      { ja: "明日は晴れるでしょう。", reading: "あしたははれるでしょう。", meaningZh: "聽日應該會晴。" },
      { ja: "彼は来ないだろう。", reading: "かれはこないだろう。", meaningZh: "佢大概唔會嚟。" }
    ],
    tipsZh: [
      "推量：說話人推測，唔係百分之百。",
      "天氣／意見場合常用でしょう。"
    ],
    practiceZh: [
      "天氣預報造句。",
      "表達意見兩句。",
      "聽力捉推量。"
    ],
  },
  "n3-2-2": {
    vocab: [
      { ja: "かもしれない", reading: "かもしれない", meaningZh: "可能" },
      { ja: "はずだ", reading: "はずだ", meaningZh: "理應" },
      { ja: "可能性", reading: "かのうせい", meaningZh: "可能性" }
    ],
    examples: [
      { ja: "雨が降るかもしれない。", reading: "あめがふるかもしれない。", meaningZh: "可能會落雨。" },
      { ja: "彼は知っているはずだ。", reading: "かれはしっているはずだ。", meaningZh: "佢理應知。" }
    ],
    tipsZh: [
      "かもしれない＝有可能；はずだ＝按理應該（根據較強）。",
      "否定：はずがない＝唔應該／冇理由。"
    ],
    practiceZh: [
      "情境判斷用邊個。",
      "整對比表。",
      "對話練習。"
    ],
  },
  "n3-3-1": {
    vocab: [
      { ja: "受身", reading: "うけみ", meaningZh: "被動" },
      { ja: "直接受身", reading: "ちょくせつうけみ", meaningZh: "直接被動" },
      { ja: "間接受身", reading: "かんせつうけみ", meaningZh: "間接被動" },
      { ja: "迷惑", reading: "めいわく", meaningZh: "麻煩" }
    ],
    examples: [
      { ja: "妹に日記を読まれた。", reading: "いもうとににっきをよまれた。", meaningZh: "日記俾細妹睇咗。" },
      { ja: "雨に降られた。", reading: "あめにふられた。", meaningZh: "落雨搞到我（間接受害）。" }
    ],
    tipsZh: [
      "直接被動：對象被作用；間接（迷惑）被動：受牽連。",
      "中級要識分辨語感。"
    ],
    practiceZh: [
      "分類例句。",
      "抱怨情境造句。",
      "改寫主動→被動。"
    ],
  },
  "n3-3-2": {
    vocab: [
      { ja: "使役受身", reading: "しえきうけみ", meaningZh: "使役被動" },
      { ja: "覚えさせられる", reading: "おぼえさせられる", meaningZh: "被迫記" },
      { ja: "毎日", reading: "まいにち", meaningZh: "每日" }
    ],
    examples: [
      { ja: "毎日漢字を覚えさせられます。", reading: "まいにちかんじをおぼえさせられます。", meaningZh: "每日被人迫背漢字。" },
      { ja: "残業をさせられた。", reading: "ざんぎょうをさせられた。", meaningZh: "被迫加班。" }
    ],
    tipsZh: [
      "使役被動＝被迫做；職場／學校故事好常見。",
      "變化長，建議由ます形逐步推。"
    ],
    practiceZh: [
      "變化練習。",
      "寫職場短故事。",
      "小測。"
    ],
  },
  "n3-4-1": {
    vocab: [
      { ja: "件名", reading: "けんめい", meaningZh: "主旨" },
      { ja: "いつもお世話になっております", reading: "いつもおせわになっております", meaningZh: "一向蒙關照" },
      { ja: "欠席", reading: "けっせき", meaningZh: "缺席" },
      { ja: "お願い", reading: "おねがい", meaningZh: "請求" }
    ],
    examples: [
      { ja: "欠席の連絡をいたします。", reading: "けっせきのれんらくをいたします。", meaningZh: "通知會缺席。" },
      { ja: "ご確認のほどお願いいたします。", reading: "ごかくにんのほどお願いいたします。", meaningZh: "懇請確認。" }
    ],
    tipsZh: [
      "商務郵件：挨拶→要件→締め。",
      "避免太口語；用いたします等謙譲。"
    ],
    practiceZh: [
      "寫請假信。",
      "改寫粗魯句。",
      "對照範本。"
    ],
  },
  "n3-4-2": {
    vocab: [
      { ja: "受付", reading: "うけつけ", meaningZh: "接待處" },
      { ja: "少々", reading: "しょうしょう", meaningZh: "稍微" },
      { ja: "お待ちいただけますか", reading: "おまちいただけますか", meaningZh: "可唔可以稍等" },
      { ja: "かしこまりました", reading: "かしこまりました", meaningZh: "明白（敬）" }
    ],
    examples: [
      { ja: "少々お待ちいただけますか。", reading: "しょうしょうおまちいただけますか。", meaningZh: "可唔可以稍等？" },
      { ja: "かしこまりました。", reading: "かしこまりました。", meaningZh: "好嘅／明白。" }
    ],
    tipsZh: [
      "電話：名乘→確認對方→轉述／留話。",
      "いただけますか 比 ください 更婉曲。"
    ],
    practiceZh: [
      "跟讀腳本。",
      "錄音。",
      "角色扮演。"
    ],
  },
  "n3-5-1": {
    vocab: [
      { ja: "経済", reading: "けいざい", meaningZh: "經濟" },
      { ja: "社会", reading: "しゃかい", meaningZh: "社會" },
      { ja: "環境", reading: "かんきょう", meaningZh: "環境" },
      { ja: "影響", reading: "えいきょう", meaningZh: "影響" },
      { ja: "関係", reading: "かんけい", meaningZh: "關係" }
    ],
    examples: [
      { ja: "経済に影響する。", reading: "けいざいにえいきょうする。", meaningZh: "影響經濟。" },
      { ja: "社会問題を考える。", reading: "しゃかいもんだいをかんがえる。", meaningZh: "思考社會問題。" }
    ],
    tipsZh: [
      "漢音二字熟語：前後都傾向音讀。",
      "閃卡要連讀法一齊背。"
    ],
    practiceZh: [
      "50 詞分週背。",
      "聽寫。",
      "造句五則。"
    ],
  },
  "n3-5-2": {
    vocab: [
      { ja: "橋", reading: "はし", meaningZh: "橋" },
      { ja: "箸", reading: "はし", meaningZh: "筷子" },
      { ja: "端", reading: "はし", meaningZh: "邊／末端" },
      { ja: "期間", reading: "きかん", meaningZh: "期間" }
    ],
    examples: [
      { ja: "箸で食べます。", reading: "はしでたべます。", meaningZh: "用筷子食。" },
      { ja: "橋の端に立つ。", reading: "はしのはしにたつ。", meaningZh: "企喺橋邊。" }
    ],
    tipsZh: [
      "同音異義靠漢字同語境分辨。",
      "聽力題成日考呢類——先想場景。"
    ],
    practiceZh: [
      "聽音選字。",
      "語境練習。",
      "錯題本。"
    ],
  },
  "n3-6-1": {
    vocab: [
      { ja: "見出し", reading: "みだし", meaningZh: "標題" },
      { ja: "リード", reading: "リード", meaningZh: "導言" },
      { ja: "結論", reading: "けつろん", meaningZh: "結論" },
      { ja: "記事", reading: "きじ", meaningZh: "報導" }
    ],
    examples: [
      { ja: "見出しを先に読む。", reading: "みだしをさきによむ。", meaningZh: "先讀標題。" },
      { ja: "結論をまとめる。", reading: "けつろんをまとめる。", meaningZh: "總結結論。" }
    ],
    tipsZh: [
      "新聞結構：標題→リード→本文→結論。",
      "摘要練習：每段一句。"
    ],
    practiceZh: [
      "劃結構。",
      "摘要三句。",
      "生詞表＋讀法。"
    ],
  },
  "n3-6-2": {
    vocab: [
      { ja: "増加", reading: "ぞうか", meaningZh: "增加" },
      { ja: "減少", reading: "げんしょう", meaningZh: "減少" },
      { ja: "割合", reading: "わりあい", meaningZh: "比例" },
      { ja: "比べる", reading: "くらべる", meaningZh: "比較" }
    ],
    examples: [
      { ja: "売上が増加した。", reading: "うりあげがぞうかした。", meaningZh: "營業額增加咗。" },
      { ja: "前年と比べて減った。", reading: "ぜんねんとくらべてへった。", meaningZh: "同前年比減少咗。" }
    ],
    tipsZh: [
      "圖表句型：増加する／減少する／横ばい。",
      "口頭說明要有數字＋趨勢＋原因。"
    ],
    practiceZh: [
      "描述一張圖。",
      "錄影一分鐘。",
      "同伴互評。"
    ],
  },
  "n3-7-1": {
    vocab: [
      { ja: "てしまう", reading: "てしまう", meaningZh: "做完／遺憾地做了" },
      { ja: "ことになる", reading: "ことになる", meaningZh: "變成…（結果）" },
      { ja: "決まる", reading: "きまる", meaningZh: "決定" }
    ],
    examples: [
      { ja: "宿題をやってしまった。", reading: "しゅくだいをやってしまった。", meaningZh: "功課做晒／（遺憾）做完咗。" },
      { ja: "来年日本へ行くことになった。", reading: "らいねんにほんへいくことになった。", meaningZh: "決定咗聽年去日本。" }
    ],
    tipsZh: [
      "てしまう：完成或遺憾；ことになる：外在決定結果。",
      "日記好常用呢兩種。"
    ],
    practiceZh: [
      "日記用てしまう。",
      "規則說明用ことになる。",
      "聽力。"
    ],
  },
  "n3-7-2": {
    vocab: [
      { ja: "感動", reading: "かんどう", meaningZh: "感動" },
      { ja: "失望", reading: "しつぼう", meaningZh: "失望" },
      { ja: "便利", reading: "べんり", meaningZh: "方便" },
      { ja: "残念", reading: "ざんねん", meaningZh: "可惜" }
    ],
    examples: [
      { ja: "映画に感動した。", reading: "えいがにかんどうした。", meaningZh: "俾電影感動到。" },
      { ja: "残念です。", reading: "ざんねんです。", meaningZh: "好可惜。" }
    ],
    tipsZh: [
      "評價詞幫你寫感想段落。",
      "搭配：に感動する、に失望する。"
    ],
    practiceZh: [
      "影評五句。",
      "詞彙地圖。",
      "對話分享。"
    ],
  },
  "n3-8-1": {
    vocab: [
      { ja: "話題", reading: "わだい", meaningZh: "話題" },
      { ja: "転換", reading: "てんかん", meaningZh: "轉換" },
      { ja: "結論", reading: "けつろん", meaningZh: "結論" },
      { ja: "メモ", reading: "メモ", meaningZh: "筆記" }
    ],
    examples: [
      { ja: "話題が変わった。", reading: "わだいがかわった。", meaningZh: "話題轉咗。" },
      { ja: "結論を聞き逃すな。", reading: "けつろんをききのがすな。", meaningZh: "唔好聽漏結論。" }
    ],
    tipsZh: [
      "長對話：記誰提出新話題、最後決定係咩。",
      "轉折詞：でも、実は、ところで。"
    ],
    practiceZh: [
      "邊聽邊筆記。",
      "答題。",
      "對腳本。"
    ],
  },
  "n3-8-2": {
    vocab: [
      { ja: "即時応答", reading: "そくじおうとう", meaningZh: "即時回應" },
      { ja: "返事", reading: "へんじ", meaningZh: "答覆" },
      { ja: "適切", reading: "てきせつ", meaningZh: "恰當" }
    ],
    examples: [
      { ja: "今でなくてもいいですよ。", reading: "いまでなくてもいいですよ。", meaningZh: "唔使而家都得。" },
      { ja: "ぜひお願いします。", reading: "ぜひおねがいします。", meaningZh: "務必拜託。" }
    ],
    tipsZh: [
      "即時回應考語感同禮貌程度。",
      "先判斷：承諾／拒絕／確認／緩和。"
    ],
    practiceZh: [
      "連續 10 題。",
      "分析錯誤。",
      "跟讀正確回應。"
    ],
  },
  "n3-9-1": {
    vocab: [
      { ja: "説明文", reading: "せつめいぶん", meaningZh: "說明文" },
      { ja: "構成", reading: "こうせい", meaningZh: "結構" },
      { ja: "例", reading: "れい", meaningZh: "例子" },
      { ja: "まとめ", reading: "まとめ", meaningZh: "總結" }
    ],
    examples: [
      { ja: "まず構成を決める。", reading: "まずこうせいをきめる。", meaningZh: "首先決定結構。" },
      { ja: "例を挙げて説明する。", reading: "れいをあげてせつめいする。", meaningZh: "舉例說明。" }
    ],
    tipsZh: [
      "200 字說明：引入→特點→例子→收結。",
      "家鄉／興趣題好適合練習。"
    ],
    practiceZh: [
      "列大綱。",
      "寫草稿。",
      "自我修改。"
    ],
  },
  "n3-9-2": {
    vocab: [
      { ja: "賛成", reading: "さんせい", meaningZh: "贊成" },
      { ja: "反対", reading: "はんたい", meaningZh: "反對" },
      { ja: "理由", reading: "りゆう", meaningZh: "理由" },
      { ja: "例えば", reading: "たとえば", meaningZh: "例如" }
    ],
    examples: [
      { ja: "私は賛成です。理由は二つあります。", reading: "わたしはさんせいです。りゆうはふたつあります。", meaningZh: "我贊成，有兩個理由。" },
      { ja: "一方、反対意見もある。", reading: "いっぽう、はんたいいけんもある。", meaningZh: "另一方面亦有反對意見。" }
    ],
    tipsZh: [
      "意見文：立場→理由→例子→讓步→再強調。",
      "接續詞令段落更似 N3 書面。"
    ],
    practiceZh: [
      "選題寫 150 字。",
      "加接續詞。",
      "朗讀。"
    ],
  },
  "n3-10-1": {
    vocab: [
      { ja: "総復習", reading: "そうふくしゅう", meaningZh: "總複習" },
      { ja: "助詞", reading: "じょし", meaningZh: "助詞" },
      { ja: "敬語", reading: "けいご", meaningZh: "敬語" },
      { ja: "条件", reading: "じょうけん", meaningZh: "條件" }
    ],
    examples: [
      { ja: "文法を総復習する。", reading: "ぶんぽうをそうふくしゅうする。", meaningZh: "總複習文法。" },
      { ja: "弱点リストを作る。", reading: "じゃくてんリストをつくる。", meaningZh: "整弱項清單。" }
    ],
    tipsZh: [
      "用心智圖串：助詞・條件・敬語・受身使役。",
      "每類留兩條代表句＋讀法。"
    ],
    practiceZh: [
      "心智圖。",
      "模擬文法卷。",
      "弱項清單。"
    ],
  },
  "n3-10-2": {
    vocab: [
      { ja: "本番", reading: "ほんばん", meaningZh: "正式考試" },
      { ja: "配分", reading: "はいぶん", meaningZh: "時間分配" },
      { ja: "得点", reading: "とくてん", meaningZh: "得分" }
    ],
    examples: [
      { ja: "本番のつもりで受ける。", reading: "ほんばんのつもりでうける。", meaningZh: "當正式考噉考。" },
      { ja: "時間配分を守る。", reading: "じかんはいぶんをまもる。", meaningZh: "守時間分配。" }
    ],
    tipsZh: [
      "接近正式節奏：唔好中途停錶。",
      "考完訂 N2：每週一篇論說＋商務套語。"
    ],
    practiceZh: [
      "全卷計時。",
      "分數分析。",
      "訂 N2 路線。"
    ],
  },
  "n2-1-1": {
    vocab: [
      { ja: "わけだ", reading: "わけだ", meaningZh: "即係話／難怪" },
      { ja: "はずだ", reading: "はずだ", meaningZh: "理應" },
      { ja: "べきだ", reading: "べきだ", meaningZh: "應該（義務）" },
      { ja: "判断", reading: "はんだん", meaningZh: "判斷" }
    ],
    examples: [
      { ja: "それで遅れたわけだ。", reading: "それでおくれたわけだ。", meaningZh: "難怪會遲到。" },
      { ja: "約束は守るべきだ。", reading: "やくそくはまもるべきだ。", meaningZh: "約定應該守。" }
    ],
    tipsZh: [
      "わけだ：推論結論；はずだ：按證據理應；べきだ：規範上應該。",
      "社論句子常用呢組判斷表現。"
    ],
    practiceZh: [
      "整對照表。",
      "分析社論兩句。",
      "造句十則（選三型）。"
    ],
  },
  "n2-1-2": {
    vocab: [
      { ja: "に違いない", reading: "にちがいない", meaningZh: "一定係" },
      { ja: "かねない", reading: "かねない", meaningZh: "搞不好會（負面）" },
      { ja: "確信", reading: "かくしん", meaningZh: "確信" },
      { ja: "リスク", reading: "リスク", meaningZh: "風險" }
    ],
    examples: [
      { ja: "彼が犯人に違いない。", reading: "かれがはんにんにちがいない。", meaningZh: "一定係佢做。" },
      { ja: "失敗しかねない。", reading: "しっぱいしかねない。", meaningZh: "搞不好會失敗。" }
    ],
    tipsZh: [
      "に違いない＝確信度高；かねない＝有負面可能性。",
      "新聞風險描述好常用かねない。"
    ],
    practiceZh: [
      "新聞改寫。",
      "風險描述三句。",
      "小測。"
    ],
  },
  "n2-2-1": {
    vocab: [
      { ja: "つつ", reading: "つつ", meaningZh: "一邊…／雖然（書面）" },
      { ja: "ながらも", reading: "ながらも", meaningZh: "雖然…仍然" },
      { ja: "知る", reading: "しる", meaningZh: "知" }
    ],
    examples: [
      { ja: "悪いと知りつつ言ってしまった。", reading: "わるいとしりつついってしまった。", meaningZh: "明知唔好都講咗出嚟。" },
      { ja: "小さいながらも店は繁盛している。", reading: "ちいさいながらもみせははんじょうしている。", meaningZh: "舖頭細但生意旺。" }
    ],
    tipsZh: [
      "つつ／ながらも 偏書面，表逆接或並行。",
      "口語多數用ながら、でも。"
    ],
    practiceZh: [
      "簡化文學句。",
      "寫兩句複雜句。",
      "聽力。"
    ],
  },
  "n2-2-2": {
    vocab: [
      { ja: "ばかりか", reading: "ばかりか", meaningZh: "唔單止" },
      { ja: "のみならず", reading: "のみならず", meaningZh: "不僅（書面）" },
      { ja: "強調", reading: "きょうちょう", meaningZh: "強調" }
    ],
    examples: [
      { ja: "英語ばかりか中国語も話せる。", reading: "えいごばかりかちゅうごくごもはなせる。", meaningZh: "唔單止英文，中文都會講。" },
      { ja: "国内のみならず海外でも人気だ。", reading: "こくないのみならずかいがいでもにんきだ。", meaningZh: "唔單止國內，海外都受歡迎。" }
    ],
    tipsZh: [
      "添加強調：前項已經夠，後項再加碼。",
      "演講稿好適合用。"
    ],
    practiceZh: [
      "改寫簡單句。",
      "演講稿兩句。",
      "閱讀填空。"
    ],
  },
  "n2-3-1": {
    vocab: [
      { ja: "実施", reading: "じっし", meaningZh: "實施" },
      { ja: "検討", reading: "けんとう", meaningZh: "研究／檢討" },
      { ja: "導入", reading: "どうにゅう", meaningZh: "引入" },
      { ja: "方針", reading: "ほうしん", meaningZh: "方針" },
      { ja: "発表", reading: "はっぴょう", meaningZh: "發表" }
    ],
    examples: [
      { ja: "新制度を導入する。", reading: "しんせいどをどうにゅうする。", meaningZh: "引入新制度。" },
      { ja: "対策を検討している。", reading: "たいさくをけんとうしている。", meaningZh: "正研究對策。" }
    ],
    tipsZh: [
      "報紙常用サ變漢語詞：実施・検討・導入・拡大。",
      "標題翻譯時保留書面語感。"
    ],
    practiceZh: [
      "50 詞卡＋讀法。",
      "標題翻譯五則。",
      "聽新聞摘要。"
    ],
  },
  "n2-3-2": {
    vocab: [
      { ja: "書き言葉", reading: "かきことば", meaningZh: "書面語" },
      { ja: "話し言葉", reading: "はなしことば", meaningZh: "口語" },
      { ja: "である", reading: "である", meaningZh: "係（書面）" },
      { ja: "です", reading: "です", meaningZh: "係（丁寧）" }
    ],
    examples: [
      { ja: "問題である。→問題です。", reading: "もんだいである。→もんだいです。", meaningZh: "書面→口語。" },
      { ja: "〜しなければならない→〜しないといけない", reading: "〜しなければならない→〜しないといけない", meaningZh: "義務表達文體差" }
    ],
    tipsZh: [
      "正式改寫：刪口語終助詞、換である體、用漢語詞。",
      "會議紀要偏書面。"
    ],
    practiceZh: [
      "改十句。",
      "寫會議紀要。",
      "互評。"
    ],
  },
  "n2-4-1": {
    vocab: [
      { ja: "一石二鳥", reading: "いっせきにちょう", meaningZh: "一石二鳥" },
      { ja: "諸行無常", reading: "しょぎょうむじょう", meaningZh: "諸行無常" },
      { ja: "臨機応変", reading: "りんきおうへん", meaningZh: "臨機應變" },
      { ja: "因果関係", reading: "いんがかんけい", meaningZh: "因果關係" }
    ],
    examples: [
      { ja: "一石二鳥の案だ。", reading: "いっせきにちょうのあんだ。", meaningZh: "一石二鳥嘅方案。" },
      { ja: "臨機応変に対応する。", reading: "りんきおうへんにたいおうする。", meaningZh: "臨機應變噉應對。" }
    ],
    tipsZh: [
      "難讀熟語要整組背讀法。",
      "考試常考：睇漢字選讀音。"
    ],
    practiceZh: [
      "閃卡 40。",
      "聽寫。",
      "語境選擇。"
    ],
  },
  "n2-4-2": {
    vocab: [
      { ja: "見る", reading: "みる", meaningZh: "睇（一般）" },
      { ja: "観る", reading: "みる", meaningZh: "觀賞" },
      { ja: "診る", reading: "みる", meaningZh: "診症" },
      { ja: "視る", reading: "みる", meaningZh: "注視／檢視" }
    ],
    examples: [
      { ja: "映画を観る。", reading: "えいがをみる。", meaningZh: "睇戲（觀賞）。" },
      { ja: "医者が患者を診る。", reading: "いしゃがかんじゃをみる。", meaningZh: "醫生診症。" }
    ],
    tipsZh: [
      "同訓異字：讀法相同但漢字語感不同。",
      "寫作時按語境選字。"
    ],
    practiceZh: [
      "配對練習。",
      "造句四則。",
      "錯題本。"
    ],
  },
  "n2-5-1": {
    vocab: [
      { ja: "提案", reading: "ていあん", meaningZh: "提案" },
      { ja: "賛成", reading: "さんせい", meaningZh: "贊成" },
      { ja: "保留", reading: "ほりゅう", meaningZh: "保留" },
      { ja: "検討", reading: "けんとう", meaningZh: "研究" },
      { ja: "件", reading: "けん", meaningZh: "事項" }
    ],
    examples: [
      { ja: "その件について検討したいと思います。", reading: "そのけんについてけんとうしたいとおもいます。", meaningZh: "想就呢件事再研究下。" },
      { ja: "提案に賛成です。", reading: "ていあんにさんせいです。", meaningZh: "贊成提案。" }
    ],
    tipsZh: [
      "會議：提案→質疑→贊成／保留→結論。",
      "委婉：検討したいと思います。"
    ],
    practiceZh: [
      "會議角色扮演。",
      "用語表。",
      "錄音。"
    ],
  },
  "n2-5-2": {
    vocab: [
      { ja: "報告", reading: "ほうこく", meaningZh: "報告" },
      { ja: "資料", reading: "しりょう", meaningZh: "資料" },
      { ja: "結論", reading: "けつろん", meaningZh: "結論" },
      { ja: "質疑", reading: "しつぎ", meaningZh: "提問" }
    ],
    examples: [
      { ja: "まず資料をご覧ください。", reading: "まずしりょうをごらんください。", meaningZh: "請先睇資料。" },
      { ja: "以上が本日の報告です。", reading: "いじょうがほんじつのほうこくです。", meaningZh: "以上係今日報告。" }
    ],
    tipsZh: [
      "簡報結構：開場→數據→解釋→收結→Q&A。",
      "數字要讀得清楚（億・万）。"
    ],
    practiceZh: [
      "三分鐘簡報。",
      "投影稿大綱。",
      "Q&A 練習。"
    ],
  },
  "n2-6-1": {
    vocab: [
      { ja: "主張", reading: "しゅちょう", meaningZh: "主張" },
      { ja: "理由", reading: "りゆう", meaningZh: "理由" },
      { ja: "反駁", reading: "はんばく", meaningZh: "反駁" },
      { ja: "論説", reading: "ろんせつ", meaningZh: "論說" }
    ],
    examples: [
      { ja: "筆者の主張を探す。", reading: "ひっしゃのしゅちょうをさがす。", meaningZh: "搵作者主張。" },
      { ja: "反駁にどう応じるか。", reading: "はんばくにどうおうじるか。", meaningZh: "點回應反駁。" }
    ],
    tipsZh: [
      "論說文：主張－理由－例子－反駁－再主張。",
      "摘要 80 字只留論點鏈。"
    ],
    practiceZh: [
      "劃結構。",
      "作者意圖題。",
      "摘要 80 字。"
    ],
  },
  "n2-6-2": {
    vocab: [
      { ja: "内容一致", reading: "ないよういっち", meaningZh: "內容一致" },
      { ja: "罠", reading: "わな", meaningZh: "陷阱" },
      { ja: "言い換え", reading: "いいかえ", meaningZh: "換講法" }
    ],
    examples: [
      { ja: "本文に書いてあるか確認する。", reading: "ほんぶんにかいてあるかかくにんする。", meaningZh: "確認文中有冇寫。" },
      { ja: "極端な選択肢に注意。", reading: "きょくたんなせんたくしにちゅうい。", meaningZh: "小心極端選項。" }
    ],
    tipsZh: [
      "技巧：排除「文中無」「過度推論」「絕對詞」。",
      "一致題常考換講法（言い換え）。"
    ],
    practiceZh: [
      "三篇練習。",
      "錯因分類。",
      "計時。"
    ],
  },
  "n2-7-1": {
    vocab: [
      { ja: "講義", reading: "こうぎ", meaningZh: "講座" },
      { ja: "要点", reading: "ようてん", meaningZh: "要點" },
      { ja: "例示", reading: "れいじ", meaningZh: "舉例" },
      { ja: "定義", reading: "ていぎ", meaningZh: "定義" }
    ],
    examples: [
      { ja: "定義をまずメモする。", reading: "ていぎをまずメモする。", meaningZh: "先記定義。" },
      { ja: "例は後で整理する。", reading: "れいはあとでせいりする。", meaningZh: "例子之後再整理。" }
    ],
    tipsZh: [
      "講座筆記：定義／例子／例外／結論分欄。",
      "唔好逐字抄，記關鍵詞同箭嘴關係。"
    ],
    practiceZh: [
      "聽五分鐘。",
      "整理筆記。",
      "答題。"
    ],
  },
  "n2-7-2": {
    vocab: [
      { ja: "統合", reading: "とうごう", meaningZh: "整合" },
      { ja: "複数", reading: "ふくすう", meaningZh: "多個" },
      { ja: "情報", reading: "じょうほう", meaningZh: "資訊" },
      { ja: "判断", reading: "はんだん", meaningZh: "判斷" }
    ],
    examples: [
      { ja: "二つの話を統合して答える。", reading: "ふたつのはなしをとうごうしてこたえる。", meaningZh: "整合兩段說話作答。" },
      { ja: "矛盾がないか確認する。", reading: "むじゅんがないかかくにんする。", meaningZh: "確認有冇矛盾。" }
    ],
    tipsZh: [
      "統合理解：跨段資訊合併，留意誰講咩。",
      "畫關係圖好有幫助。"
    ],
    practiceZh: [
      "練習整合題。",
      "畫關係圖。",
      "覆盤。"
    ],
  },
  "n2-8-1": {
    vocab: [
      { ja: "ものだ", reading: "ものだ", meaningZh: "感慨／常理" },
      { ja: "ことだ", reading: "ことだ", meaningZh: "勸告（你應…）" },
      { ja: "忠告", reading: "ちゅうこく", meaningZh: "忠告" }
    ],
    examples: [
      { ja: "子供のころはよく遊んだものだ。", reading: "こどものころはよくあそんだものだ。", meaningZh: "細個時成日玩啊（感慨）。" },
      { ja: "もっと勉強することだ。", reading: "もっとべんきょうすることだ。", meaningZh: "你應該再多用功。" }
    ],
    tipsZh: [
      "ものだ：感慨／普遍道理；ことだ：對對方勸告。",
      "語氣細微，寫作唔好亂用。"
    ],
    practiceZh: [
      "對照例句。",
      "勸告對話。",
      "寫作運用兩句。"
    ],
  },
  "n2-8-2": {
    vocab: [
      { ja: "わけではない", reading: "わけではない", meaningZh: "並非就係…" },
      { ja: "というものでもない", reading: "というものでもない", meaningZh: "亦唔係話…" },
      { ja: "部分否定", reading: "ぶぶんひてい", meaningZh: "部分否定" }
    ],
    examples: [
      { ja: "行きたくないわけではない。", reading: "いきたくないわけではない。", meaningZh: "並唔係唔想去。" },
      { ja: "お金があれば幸せというものでもない。", reading: "おかねがあればしあわせというものでもない。", meaningZh: "亦唔係有錢就一定幸福。" }
    ],
    tipsZh: [
      "部分否定用嚟緩和極端說法。",
      "辯論同社論好常見。"
    ],
    practiceZh: [
      "改寫極端句。",
      "辯論練習。",
      "小測。"
    ],
  },
  "n2-9-1": {
    vocab: [
      { ja: "環境", reading: "かんきょう", meaningZh: "環境" },
      { ja: "少子化", reading: "しょうしか", meaningZh: "少子化" },
      { ja: "課題", reading: "かだい", meaningZh: "課題" },
      { ja: "対策", reading: "たいさく", meaningZh: "對策" }
    ],
    examples: [
      { ja: "少子化は大きな課題だ。", reading: "しょうしかはおおきなかだいだ。", meaningZh: "少子化係大課題。" },
      { ja: "環境対策が急がれる。", reading: "かんきょうたいさくがいそがれる。", meaningZh: "環境對策急需推進。" }
    ],
    tipsZh: [
      "社會議題詞：課題・対策・影響・背景。",
      "讀完整理：問題→原因→對策。"
    ],
    practiceZh: [
      "詞彙表＋讀法。",
      "立場摘要。",
      "討論三點。"
    ],
  },
  "n2-9-2": {
    vocab: [
      { ja: "随筆", reading: "ずいひつ", meaningZh: "隨筆" },
      { ja: "修辞", reading: "しゅうじ", meaningZh: "修辭" },
      { ja: "比喩", reading: "ひゆ", meaningZh: "比喻" },
      { ja: "文体", reading: "ぶんたい", meaningZh: "文體" }
    ],
    examples: [
      { ja: "比喩に注目する。", reading: "ひゆにちゅうもくする。", meaningZh: "留意比喻。" },
      { ja: "筆者の語気を読む。", reading: "ひっしゃのごちょうをよむ。", meaningZh: "讀作者語氣。" }
    ],
    tipsZh: [
      "隨筆重語氣同修辭，唔只資訊。",
      "仿寫時保留一句修辭。"
    ],
    practiceZh: [
      "找修辭。",
      "仿寫段落。",
      "朗讀。"
    ],
  },
  "n2-10-1": {
    vocab: [
      { ja: "言語知識", reading: "げんごちしき", meaningZh: "言語知識" },
      { ja: "語彙", reading: "ごい", meaningZh: "語彙" },
      { ja: "文法", reading: "ぶんぽう", meaningZh: "文法" }
    ],
    examples: [
      { ja: "言語知識の弱点を潰す。", reading: "げんごちしきのじゃくてんをつぶす。", meaningZh: "消滅言語知識弱項。" },
      { ja: "毎日二十問解く。", reading: "まいにちにじゅうもんとく。", meaningZh: "每日做 20 題。" }
    ],
    tipsZh: [
      "混合卷按錯型分類：近義／接續／漢字讀法。",
      "每日小額練習好過一次爆量。"
    ],
    practiceZh: [
      "計時完成。",
      "弱項地圖。",
      "每日 20 題計劃。"
    ],
  },
  "n2-10-2": {
    vocab: [
      { ja: "全科", reading: "ぜんか", meaningZh: "全科" },
      { ja: "換算", reading: "かんさん", meaningZh: "換算" },
      { ja: "仕上げ", reading: "しあげ", meaningZh: "收尾" }
    ],
    examples: [
      { ja: "全科の模擬をする。", reading: "ぜんかのもぎをする。", meaningZh: "做全科模擬。" },
      { ja: "得点を換算する。", reading: "とくてんをかんさんする。", meaningZh: "換算分數。" }
    ],
    tipsZh: [
      "接近正式時長，練體力同節奏。",
      "之後訂 N1：抽象詞＋高級文法精準度。"
    ],
    practiceZh: [
      "全卷。",
      "分數換算。",
      "訂 N1 衝刺。"
    ],
  },
  "n1-1-1": {
    vocab: [
      { ja: "んがため", reading: "んがため", meaningZh: "為咗…（文語）" },
      { ja: "ともなく", reading: "ともなく", meaningZh: "唔知邊…／無意中" },
      { ja: "文語", reading: "ぶんご", meaningZh: "文語" }
    ],
    examples: [
      { ja: "勝たんがため練習する。", reading: "かたんがためれんしゅうする。", meaningZh: "為咗贏而練習。" },
      { ja: "どこからともなく声がした。", reading: "どこからともなくこえがした。", meaningZh: "唔知從邊傳嚟聲。" }
    ],
    tipsZh: [
      "文語殘留句型多見於書面／文學；要識改寫現代語。",
      "先記意思同接續，再造句。"
    ],
    practiceZh: [
      "例句精讀＋讀法。",
      "改寫現代語。",
      "造句五則。"
    ],
  },
  "n1-1-2": {
    vocab: [
      { ja: "たらんばかり", reading: "たらんばかり", meaningZh: "幾乎要…" },
      { ja: "が早いか", reading: "がはやいか", meaningZh: "一…就" },
      { ja: "瞬間", reading: "しゅんかん", meaningZh: "瞬間" }
    ],
    examples: [
      { ja: "泣かんばかりの顔", reading: "なかんばかりのかお", meaningZh: "幾乎要喊嘅表情" },
      { ja: "ベルが鳴るが早いか飛び出した。", reading: "ベルがなるがはやいかとびだした。", meaningZh: "鐘一響就衝咗出去。" }
    ],
    tipsZh: [
      "たらんばかり：程度幾乎；が早いか：前後幾乎無間隔。",
      "同近義（や否や等）一齊對照。"
    ],
    practiceZh: [
      "對照近義。",
      "文學句分析。",
      "小測。"
    ],
  },
  "n1-2-1": {
    vocab: [
      { ja: "につけ", reading: "につけ", meaningZh: "每當／無論" },
      { ja: "に際して", reading: "にさいして", meaningZh: "值…之際" },
      { ja: "にあたって", reading: "にあたって", meaningZh: "正當…之時" }
    ],
    examples: [
      { ja: "何事につけ慎重だ。", reading: "なにごとにつけしんちょうだ。", meaningZh: "無論咩事都好慎重。" },
      { ja: "卒業に際して一言。", reading: "そつぎょうにさいしてひとこと。", meaningZh: "畢業之際講兩句。" }
    ],
    tipsZh: [
      "時機近義：に際して／にあたって 較正式；につけ 另有「每當」用法。",
      "選擇題靠前後文語氣。"
    ],
    practiceZh: [
      "選擇題 20。",
      "情境配對。",
      "作文運用。"
    ],
  },
  "n1-2-2": {
    vocab: [
      { ja: "限り", reading: "かぎり", meaningZh: "只要／限於" },
      { ja: "に限って", reading: "にかぎって", meaningZh: "偏偏／僅限" },
      { ja: "に限らず", reading: "にかぎらず", meaningZh: "唔限於" }
    ],
    examples: [
      { ja: "知っている限り教える。", reading: "しっているかぎりおしえる。", meaningZh: "喺我所知範圍內會教。" },
      { ja: "彼に限って嘘はつかない。", reading: "かれにかぎってうそはつかない。", meaningZh: "偏偏佢唔會講大話。" }
    ],
    tipsZh: [
      "限定表現細分：範圍／例外強調／擴大範圍。",
      "に限って 常帶「偏偏」語感。"
    ],
    practiceZh: [
      "對照表。",
      "改錯。",
      "對話。"
    ],
  },
  "n1-3-1": {
    vocab: [
      { ja: "概念", reading: "がいねん", meaningZh: "概念" },
      { ja: "観点", reading: "かんてん", meaningZh: "觀點" },
      { ja: "枠組み", reading: "わくぐみ", meaningZh: "框架" },
      { ja: "前提", reading: "ぜんてい", meaningZh: "前提" },
      { ja: "示唆", reading: "しさ", meaningZh: "暗示／啟示" }
    ],
    examples: [
      { ja: "新しい枠組みが必要だ。", reading: "あたらしいわくぐみがひつようだ。", meaningZh: "需要新框架。" },
      { ja: "この概念を定義する。", reading: "このがいねんをていぎする。", meaningZh: "定義呢個概念。" }
    ],
    tipsZh: [
      "學術／社論抽象名詞要連讀法同定義一齊記。",
      "摘要時優先用呢類詞壓縮資訊。"
    ],
    practiceZh: [
      "分週背。",
      "定義配對。",
      "摘要用詞練習。"
    ],
  },
  "n1-3-2": {
    vocab: [
      { ja: "にもかかわらず", reading: "にもかかわらず", meaningZh: "儘管" },
      { ja: "ゆえに", reading: "ゆえに", meaningZh: "因此（文）" },
      { ja: "したがって", reading: "したがって", meaningZh: "因此" },
      { ja: "もっとも", reading: "もっとも", meaningZh: "不過／固然" }
    ],
    examples: [
      { ja: "雨にもかかわらず続行した。", reading: "あめにもかかわらずぞっこうした。", meaningZh: "儘管落雨仍然繼續。" },
      { ja: "証拠不十分。ゆえに無罪。", reading: "しょうこふじゅうぶん。ゆえにむざい。", meaningZh: "證據不足，因此無罪。" }
    ],
    tipsZh: [
      "高級連接詞決定論證力度。",
      "ゆえに 好書面；口語多用だから。"
    ],
    practiceZh: [
      "填空文章。",
      "寫論證段。",
      "朗讀。"
    ],
  },
  "n1-4-1": {
    vocab: [
      { ja: "一石二鳥", reading: "いっせきにちょう", meaningZh: "一石二鳥" },
      { ja: "臨機応変", reading: "りんきおうへん", meaningZh: "臨機應變" },
      { ja: "試行錯誤", reading: "しこうさくご", meaningZh: "試錯" },
      { ja: "本末転倒", reading: "ほんまつてんとう", meaningZh: "本末倒置" }
    ],
    examples: [
      { ja: "臨機応変に対応する。", reading: "りんきおうへんにたいおうする。", meaningZh: "臨機應變噉應對。" },
      { ja: "試行錯誤を重ねる。", reading: "しこうさくごをかさねる。", meaningZh: "反覆試錯。" }
    ],
    tipsZh: [
      "四字熟語：意思＋讀法＋短故事一齊記。",
      "寫作點綴一兩句即可，唔好堆砌。"
    ],
    practiceZh: [
      "30 熟語。",
      "故事配對。",
      "造句。"
    ],
  },
  "n1-4-2": {
    vocab: [
      { ja: "雪辱", reading: "せつじょく", meaningZh: "雪恥" },
      { ja: "美味しい", reading: "おいしい", meaningZh: "好味（表外訓常見）" },
      { ja: "昨日", reading: "きのう", meaningZh: "尋日（表外訓）" },
      { ja: "土産", reading: "みやげ", meaningZh: "手信" }
    ],
    examples: [
      { ja: "雪辱を果たす。", reading: "せつじょくをはたす。", meaningZh: "成功雪恥。" },
      { ja: "土産を買う。", reading: "みやげをかう。", meaningZh: "買手信。" }
    ],
    tipsZh: [
      "難讀／表外讀靠語境同固定搭配。",
      "聽寫時先想熟語定詞，再寫漢字。"
    ],
    practiceZh: [
      "聽寫。",
      "語境選讀。",
      "錯題本。"
    ],
  },
  "n1-5-1": {
    vocab: [
      { ja: "論証", reading: "ろんしょう", meaningZh: "論證" },
      { ja: "反例", reading: "はんれい", meaningZh: "反例" },
      { ja: "前提", reading: "ぜんてい", meaningZh: "前提" },
      { ja: "飛躍", reading: "ひやく", meaningZh: "跳躍（邏輯）" }
    ],
    examples: [
      { ja: "論証の飛躍がないか見る。", reading: "ろんしょうのひやくがないかみる。", meaningZh: "睇論證有冇跳躍。" },
      { ja: "反例で主張を検証する。", reading: "はんれいでしゅちょうをけんしょうする。", meaningZh: "用反例驗證主張。" }
    ],
    tipsZh: [
      "長文：追蹤前提→推論→結論，標反例位置。",
      "主旨題通常落喺結論段或轉折後。"
    ],
    practiceZh: [
      "劃論證鏈。",
      "答主旨題。",
      "寫反駁段。"
    ],
  },
  "n1-5-2": {
    vocab: [
      { ja: "比較", reading: "ひかく", meaningZh: "比較" },
      { ja: "共通点", reading: "きょうつうてん", meaningZh: "共通點" },
      { ja: "相違点", reading: "そういてん", meaningZh: "相異點" },
      { ja: "立場", reading: "たちば", meaningZh: "立場" }
    ],
    examples: [
      { ja: "二つの文章の立場を整理する。", reading: "ふたつのぶんしょうのたちばをせいりする。", meaningZh: "整理兩篇文章立場。" },
      { ja: "相違点を表にする。", reading: "そういてんをひょうにする。", meaningZh: "將相異點列表。" }
    ],
    tipsZh: [
      "比較題：先各自主張，再對齊主題軸。",
      "口述時用一方／他方。"
    ],
    practiceZh: [
      "Venn 圖。",
      "比較題。",
      "三分鐘口述。"
    ],
  },
  "n1-6-1": {
    vocab: [
      { ja: "定義", reading: "ていぎ", meaningZh: "定義" },
      { ja: "例外", reading: "れいがい", meaningZh: "例外" },
      { ja: "仮説", reading: "かせつ", meaningZh: "假說" },
      { ja: "検証", reading: "けんしょう", meaningZh: "驗證" }
    ],
    examples: [
      { ja: "定義→例→例外の順で聞く。", reading: "ていぎ→れい→れいがいのじゅんできく。", meaningZh: "按定義→例子→例外嚟聽。" },
      { ja: "仮説を検証する。", reading: "かせつをけんしょうする。", meaningZh: "驗證假說。" }
    ],
    tipsZh: [
      "學術講座筆記模板：定義／例／例外／結論。",
      "8 分鐘聽完要還原大綱。"
    ],
    practiceZh: [
      "用筆記模板。",
      "聽 8 分鐘。",
      "還原大綱。"
    ],
  },
  "n1-6-2": {
    vocab: [
      { ja: "議論", reading: "ぎろん", meaningZh: "議論" },
      { ja: "賛成派", reading: "さんせいは", meaningZh: "贊成派" },
      { ja: "慎重派", reading: "しんちょうは", meaningZh: "慎重派" },
      { ja: "妥協点", reading: "だきょうてん", meaningZh: "妥協點" }
    ],
    examples: [
      { ja: "誰がどの立場か印を付ける。", reading: "だれがどのたちばかしるしをつける。", meaningZh: "標註邊個咩立場。" },
      { ja: "妥協点を探す。", reading: "だきょうてんをさがす。", meaningZh: "搵妥協點。" }
    ],
    tipsZh: [
      "多方會議：標說話者縮寫＋立場箭嘴。",
      "整合題問「最終共識」定「未解決點」。"
    ],
    practiceZh: [
      "標註說話者。",
      "整合題。",
      "覆盤。"
    ],
  },
  "n1-7-1": {
    vocab: [
      { ja: "要約", reading: "ようやく", meaningZh: "摘要" },
      { ja: "冗長", reading: "じょうちょう", meaningZh: "冗長" },
      { ja: "論点", reading: "ろんてん", meaningZh: "論點" },
      { ja: "圧縮", reading: "あっしゅく", meaningZh: "壓縮" }
    ],
    examples: [
      { ja: "冗長な部分を削る。", reading: "じょうちょうなぶぶんをけずる。", meaningZh: "刪冗餘部分。" },
      { ja: "論点を三つに絞る。", reading: "ろんてんをみっつにしぼる。", meaningZh: "論點收窄到三個。" }
    ],
    tipsZh: [
      "日→粵／中摘要：刪例子細節，留因果同主張。",
      "120 字要可獨立理解。"
    ],
    practiceZh: [
      "刪冗餘。",
      "保留論點。",
      "對照原文。"
    ],
  },
  "n1-7-2": {
    vocab: [
      { ja: "翻訳", reading: "ほんやく", meaningZh: "翻譯" },
      { ja: "敬語", reading: "けいご", meaningZh: "敬語" },
      { ja: "自然さ", reading: "しぜんさ", meaningZh: "自然度" },
      { ja: "ニュアンス", reading: "ニュアンス", meaningZh: "語感" }
    ],
    examples: [
      { ja: "直訳を避けて自然にする。", reading: "ちょくやくをさけてしぜんにする。", meaningZh: "避免直譯，譯得自然。" },
      { ja: "敬語レベルを合わせる。", reading: "けいごレベルをあわせる。", meaningZh: "對齊敬語程度。" }
    ],
    tipsZh: [
      "粵→日：先定場面（朋友／商務），再選詞同終助詞。",
      "正式場合少用ね／よ。"
    ],
    practiceZh: [
      "譯五句。",
      "敬語調整。",
      "對照範本。"
    ],
  },
  "n1-8-1": {
    vocab: [
      { ja: "遠回し", reading: "とおまわし", meaningZh: "婉曲" },
      { ja: "含み", reading: "ふくみ", meaningZh: "含蓄" },
      { ja: "遠慮", reading: "えんりょ", meaningZh: "客氣／辭讓" },
      { ja: "断り", reading: "ことわり", meaningZh: "拒絕" }
    ],
    examples: [
      { ja: "ちょっと難しいかもしれません。", reading: "ちょっとむずかしいかもしれません。", meaningZh: "可能有啲難（婉拒）。" },
      { ja: "考えておきます。", reading: "かんがえておきます。", meaningZh: "我考慮下（常＝拒絕）。" }
    ],
    tipsZh: [
      "婉曲拒絕：避免直接いいえ，用困難／考慮／日後。",
      "批評亦可先肯定再建議。"
    ],
    practiceZh: [
      "情景應對。",
      "對照直接句。",
      "錄音。"
    ],
  },
  "n1-8-2": {
    vocab: [
      { ja: "反語", reading: "はんご", meaningZh: "反語" },
      { ja: "強調", reading: "きょうちょう", meaningZh: "強調" },
      { ja: "皮肉", reading: "ひにく", meaningZh: "諷刺" },
      { ja: "レトリック", reading: "レトリック", meaningZh: "修辭" }
    ],
    examples: [
      { ja: "これが正義だというのか。", reading: "これがせいぎだというのか。", meaningZh: "難道呢個就叫正義？（反語）" },
      { ja: "強調のために繰り返す。", reading: "きょうちょうのためにくりかえす。", meaningZh: "為強調而重複。" }
    ],
    tipsZh: [
      "識別修辭：字面意思同作者意圖可能相反。",
      "語氣改寫可練「去掉反語後嘅命題」。"
    ],
    practiceZh: [
      "標註修辭。",
      "語氣改寫。",
      "討論。"
    ],
  },
  "n1-9-1": {
    vocab: [
      { ja: "景気", reading: "けいき", meaningZh: "景氣" },
      { ja: "投資", reading: "とうし", meaningZh: "投資" },
      { ja: "革新", reading: "かくしん", meaningZh: "革新" },
      { ja: "規制", reading: "きせい", meaningZh: "規管" }
    ],
    examples: [
      { ja: "景気が回復しつつある。", reading: "けいきがかいふくしつつある。", meaningZh: "景氣正逐漸恢復。" },
      { ja: "技術革新が進む。", reading: "ぎじゅつかくしんがすすむ。", meaningZh: "技術革新推進緊。" }
    ],
    tipsZh: [
      "時事欄位詞：經濟／科技各準備 30 詞＋讀法。",
      "讀短評：背景→事件→評價。"
    ],
    practiceZh: [
      "生詞本。",
      "背景調查。",
      "立場摘要。"
    ],
  },
  "n1-9-2": {
    vocab: [
      { ja: "時事", reading: "じじ", meaningZh: "時事" },
      { ja: "概要", reading: "がいよう", meaningZh: "概要" },
      { ja: "見解", reading: "けんかい", meaningZh: "見解" },
      { ja: "根拠", reading: "こんきょ", meaningZh: "根據" }
    ],
    examples: [
      { ja: "まず概要を述べる。", reading: "まずがいようをのべる。", meaningZh: "先講概要。" },
      { ja: "見解と根拠を分けて話す。", reading: "けんかいとこんきょをわけてはなす。", meaningZh: "見解同根據分開講。" }
    ],
    tipsZh: [
      "兩分鐘簡報：概要 20 秒＋重點 60 秒＋見解 40 秒。",
      "流暢度自評：停頓、填充詞、敬體一致。"
    ],
    practiceZh: [
      "寫大綱。",
      "錄影。",
      "自評流暢度。"
    ],
  },
  "n1-10-1": {
    vocab: [
      { ja: "弱点", reading: "じゃくてん", meaningZh: "弱項" },
      { ja: "特化", reading: "とっか", meaningZh: "專項" },
      { ja: "誤答", reading: "ごとう", meaningZh: "錯答" },
      { ja: "類型", reading: "るいけい", meaningZh: "類型" }
    ],
    examples: [
      { ja: "誤答の類型を分ける。", reading: "ごとうのるいけいをわける。", meaningZh: "將錯答分類。" },
      { ja: "同じ類型を集中的に解く。", reading: "おなじるいけいをしゅうちゅうてきにとく。", meaningZh: "集中做同一類型。" }
    ],
    tipsZh: [
      "衝刺日只做錯題類型，唔好亂刷新範圍。",
      "每類型留「代表句＋讀法＋易錯點」。"
    ],
    practiceZh: [
      "分類錯題。",
      "專項 40 題。",
      "再測。"
    ],
  },
  "n1-10-2": {
    vocab: [
      { ja: "本番", reading: "ほんばん", meaningZh: "正式考試" },
      { ja: "時間配分", reading: "じかんはいぶん", meaningZh: "時間分配" },
      { ja: "見直し", reading: "みなおし", meaningZh: "檢查" },
      { ja: "戦略", reading: "せんりゃく", meaningZh: "策略" }
    ],
    examples: [
      { ja: "本番と同じ時間で受ける。", reading: "ほんばんとおなじじかんでうける。", meaningZh: "用正式時長考。" },
      { ja: "見直しの時間を残す。", reading: "みなおしのじかんをのこす。", meaningZh: "預留檢查時間。" }
    ],
    tipsZh: [
      "全真模擬後寫考前一週計劃：睡眠、薄弱項、勿開新書。",
      "分數換算只係參考，重點係穩定發揮。"
    ],
    practiceZh: [
      "嚴格計時。",
      "分數換算。",
      "考前一週計劃。"
    ],
  }
};

export function getLessonStudyContent(lessonId: string): LessonStudyContent | null {
  return LESSON_STUDY_CONTENT[lessonId] ?? null;
}

export function assertAllLessonsHaveContent(lessonIds: string[]): string[] {
  return lessonIds.filter((id) => !LESSON_STUDY_CONTENT[id]);
}
