/**
 * Build enriched Japanese lesson content for all 117 lessons.
 * Run: node scripts/jp-rich/build-all.mjs
 */
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";
import { v, e, pack } from "./helpers.mjs";
import { BEGINNER_PACKS } from "./packs-beginner.mjs";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.join(__dirname, "../..");
const base = JSON.parse(
  fs.readFileSync(path.join(__dirname, "_base.json"), "utf8")
);

function dedupe(arr, keyFn) {
  const seen = new Set();
  const out = [];
  for (const item of arr) {
    const k = keyFn(item);
    if (seen.has(k)) continue;
    seen.add(k);
    out.push(item);
  }
  return out;
}

function finalize(id, rich, baseC) {
  const vocab = dedupe(
    [...(rich?.vocab || []), ...(baseC?.vocab || [])],
    (x) => `${x.ja}::${x.reading}`
  );
  const examples = dedupe(
    [...(rich?.examples || []), ...(baseC?.examples || [])],
    (x) => `${x.ja}::${x.reading}`
  );
  let tipsZh = rich?.tipsZh?.length ? [...rich.tipsZh] : [...(baseC?.tipsZh || [])];
  let practiceZh = rich?.practiceZh?.length
    ? [...rich.practiceZh]
    : [...(baseC?.practiceZh || [])];
  let cultureTipsZh = rich?.cultureTipsZh?.length
    ? [...rich.cultureTipsZh]
    : [...(baseC?.cultureTipsZh || [])];

  // Guarantee depth with accurate study habits (not fake Japanese vocab)
  const tipPads = [
    "記新內容時一定同時記讀法：會寫漢字但唔會讀，考試同對話都會吃虧。",
    "造句要比單字更易記；每個句型至少留兩句「自己真實生活」例子。",
    "出錯唔好只改答案：寫低錯因（助詞／時態／讀音／近義）。",
    "短時間高頻複習（當日＋三日後＋一週後）比一次背很久更有效。",
  ];
  const practicePads = [
    "遮住意思，只睇日文讀出聲，再說粵語意思。",
    "遮住日文，只睇意思同讀法，默寫表面形。",
    "用本課最少五個詞寫一段 80 字短文或對話。",
    "計時兩分鐘，盡快讀完本課全部例句。",
    "第二日唔睇筆記，默寫三個最難詞＋一個例句。",
  ];
  let i = 0;
  while (tipsZh.length < 5) tipsZh.push(tipPads[i++ % tipPads.length]);
  i = 0;
  while (practiceZh.length < 5) practiceZh.push(practicePads[i++ % practicePads.length]);
  if (!cultureTipsZh.length) {
    cultureTipsZh = [
      "出聲朗讀好關鍵：日語節奏以モーラ為單位，靠口耳記會穩過淨係眼記。",
    ];
  }

  if (vocab.length < 10 || examples.length < 4) {
    console.warn(
      `[thin] ${id}: vocab=${vocab.length} examples=${examples.length}`
    );
  }

  return { vocab, examples, tipsZh, practiceZh, cultureTipsZh };
}

/** Helper to define a full pack quickly */
function P(vocab, examples, tips, practice, culture = []) {
  return pack(vocab, examples, tips, practice, culture);
}

const RICH = { ...BEGINNER_PACKS };

// Load additional level packs
const { N5_PACKS } = await import("./packs-n5.mjs");
const { N4_PACKS } = await import("./packs-n4.mjs");
const { N3_PACKS } = await import("./packs-n3.mjs");
const { N2_PACKS } = await import("./packs-n2.mjs");
const { N1_PACKS } = await import("./packs-n1.mjs");
Object.assign(RICH, N5_PACKS, N4_PACKS, N3_PACKS, N2_PACKS, N1_PACKS);

const lessonIds = Object.keys(base);
const missingRich = lessonIds.filter((id) => !RICH[id]);
if (missingRich.length) {
  console.error("Missing rich packs:", missingRich.join(", "));
  process.exit(1);
}

const CONTENT = {};
for (const id of lessonIds) {
  CONTENT[id] = finalize(id, RICH[id], base[id]);
}

function dumpVocab(item) {
  const parts = [
    `ja: ${JSON.stringify(item.ja)}`,
    `reading: ${JSON.stringify(item.reading)}`,
    `meaningZh: ${JSON.stringify(item.meaningZh)}`,
  ];
  if (item.romaji) parts.push(`romaji: ${JSON.stringify(item.romaji)}`);
  return `{ ${parts.join(", ")} }`;
}
function dumpExample(item) {
  return `{ ja: ${JSON.stringify(item.ja)}, reading: ${JSON.stringify(item.reading)}, meaningZh: ${JSON.stringify(item.meaningZh)} }`;
}
function dumpContent(c) {
  const culture = c.cultureTipsZh?.length
    ? `,\n    cultureTipsZh: [\n      ${c.cultureTipsZh.map((t) => JSON.stringify(t)).join(",\n      ")}\n    ]`
    : "";
  return `{
    vocab: [
      ${c.vocab.map(dumpVocab).join(",\n      ")}
    ],
    examples: [
      ${c.examples.map(dumpExample).join(",\n      ")}
    ],
    tipsZh: [
      ${c.tipsZh.map((t) => JSON.stringify(t)).join(",\n      ")}
    ],
    practiceZh: [
      ${c.practiceZh.map((t) => JSON.stringify(t)).join(",\n      ")}
    ]${culture}
  }`;
}

const ordered = lessonIds;
const entries = ordered
  .map((id) => `  ${JSON.stringify(id)}: ${dumpContent(CONTENT[id])}`)
  .join(",\n");

const out = `/**
 * SmartJP — 每課完整學習內容（詞彙・讀法・例句・解說・練習）
 * Generated by scripts/jp-rich/build-all.mjs — edit packs-*.mjs to regenerate.
 */

import type { LessonStudyContent } from "@/lib/japaneseCourse";

export const LESSON_STUDY_CONTENT: Record<string, LessonStudyContent> = {
${entries}
};

export function getLessonStudyContent(lessonId: string): LessonStudyContent | null {
  return LESSON_STUDY_CONTENT[lessonId] ?? null;
}

export function assertAllLessonsHaveContent(lessonIds: string[]): string[] {
  return lessonIds.filter((id) => !LESSON_STUDY_CONTENT[id]);
}
`;

const outPath = path.join(root, "src/lib/japaneseLessonContent.ts");
fs.writeFileSync(outPath, out, "utf8");

const avg = (k) =>
  (
    ordered.reduce((a, id) => a + CONTENT[id][k].length, 0) / ordered.length
  ).toFixed(1);
console.log("Wrote", outPath);
console.log("lessons", ordered.length);
console.log("avg vocab", avg("vocab"));
console.log("avg examples", avg("examples"));
console.log("avg tips", avg("tipsZh"));
console.log("avg practice", avg("practiceZh"));
